#ifndef FBE_BOARD__TYPES_H
#define FBE_BOARD__TYPES_H

typedef enum fbe_board_type_e {
    FBE_BOARD_TYPE_INVALID,
    FBE_BOARD_TYPE_X1,
    FBE_BOARD_TYPE_X1_LITE,
    FBE_BOARD_TYPE_CHAM2,
    FBE_BOARD_TYPE_X1_SUNLITE,
    FBE_BOARD_TYPE_TARPON,
    FBE_BOARD_TYPE_BARRACUDA,
    FBE_BOARD_TYPE_SNAPPER,
    FBE_BOARD_TYPE_ACADIA,
    FBE_BOARD_TYPE_GRAND_TETON,
    FBE_BOARD_TYPE_FRESHFISH,
    FBE_BOARD_TYPE_YOSEMITE,
    FBE_BOARD_TYPE_BIG_SUR,
    FBE_BOARD_TYPE_HAMMERHEAD,
    FBE_BOARD_TYPE_SLEDGEHAMMER,
    FBE_BOARD_TYPE_JACKHAMMER,
    FBE_BOARD_TYPE_VMWARE,
    FBE_BOARD_TYPE_TACKHAMMER,
    FBE_BOARD_TYPE_BOOMSLANG,
    FBE_BOARD_TYPE_DELL,
    FBE_BOARD_TYPE_FLEET,
    FBE_BOARD_TYPE_MAGNUM,
    FBE_BOARD_TYPE_ARMADA,
    FBE_BOARD_TYPE_LAST		//Must be the last value.  Used to specify the total number of values.
} fbe_board_type_t;

#endif /*FBE_BOARD__TYPES_H*/
