#ifndef _EMCPAL_IOCTL_H_
#define _EMCPAL_IOCTL_H_

#include "csx_ext.h"
#include "EmcPAL_Configuration.h"

#ifndef EMCPAL_CASE_WK

#ifdef ALAMOSA_WINDOWS_ENV
/* in Windows deployment use the Access bits in all cases */
#define EMCPAL_IOCTL_CTL_CODE(DeviceType, Function, Method, Access) \
     (((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method))

#else /*  Linux */
/* in non-Windows deployment ignore Access bits */
#define EMCPAL_IOCTL_CTL_CODE(_DeviceType, _IoctlId, _IoctlMethod, _Access) \
    CSX_P_IOCTL_CODE(_DeviceType,_IoctlId,_IoctlMethod)
#endif /* ALAMOSA_WINDOWS_ENV - STDPORT */
#define EMCPAL_IOCTL_DEVICE_TYPE_FROM_IOCTL_CODE(_IoctlCode) (((ULONG)(_IoctlCode & 0xffff0000)) >> 16)
#define EMCPAL_IOCTL_METHOD_BUFFERED CSX_P_IOCTL_METHOD_BUFFERED
#define EMCPAL_IOCTL_METHOD_IN_DIRECT CSX_P_IOCTL_METHOD_IN_DIRECT
#define EMCPAL_IOCTL_METHOD_OUT_DIRECT CSX_P_IOCTL_METHOD_OUT_DIRECT
#define EMCPAL_IOCTL_METHOD_NEITHER CSX_P_IOCTL_METHOD_NEITHER
#define EMCPAL_IOCTL_FILE_ANY_ACCESS     0
#define EMCPAL_IOCTL_FILE_DEVICE_UNKNOWN 0x22

#else
#define EMCPAL_IOCTL_CTL_CODE(DeviceType, Function, Method, Access) \
     (((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method))
#define EMCPAL_IOCTL_DEVICE_TYPE_FROM_IOCTL_CODE(_IoctlCode) (((ULONG)(_IoctlCode & 0xffff0000)) >> 16)
#define EMCPAL_IOCTL_METHOD_BUFFERED METHOD_BUFFERED
#define EMCPAL_IOCTL_METHOD_IN_DIRECT METHOD_IN_DIRECT
#define EMCPAL_IOCTL_METHOD_OUT_DIRECT METHOD_OUT_DIRECT
#define EMCPAL_IOCTL_METHOD_NEITHER METHOD_NEITHER
#define EMCPAL_IOCTL_FILE_ANY_ACCESS FILE_ANY_ACCESS
#define EMCPAL_IOCTL_FILE_DEVICE_UNKNOWN FILE_DEVICE_UNKNOWN

#endif /* EMCPAL_CASE_WK */



#ifdef ALAMOSA_WINDOWS_ENV
/*+++++++++++++++++++++++++++++++++++++ SCSI IOCTL +++++++++++++++++++++++++++++++++++++++++*/
#define EMCPAL_IOCTL_STORAGE_QUERY_PROPERTY     IOCTL_STORAGE_QUERY_PROPERTY
#define EMCPAL_IOCTL_SCSI_PASS_THROUGH          IOCTL_SCSI_PASS_THROUGH 
#define EMCPAL_IOCTL_SCSI_MINIPORT              IOCTL_SCSI_MINIPORT
#define EMCPAL_IOCTL_SCSI_GET_INQUIRY_DATA      IOCTL_SCSI_GET_INQUIRY_DATA
#define EMCPAL_IOCTL_SCSI_GET_CAPABILITIES      IOCTL_SCSI_GET_CAPABILITIES
#define EMCPAL_IOCTL_SCSI_PASS_THROUGH_DIRECT   IOCTL_SCSI_PASS_THROUGH_DIRECT
#define EMCPAL_IOCTL_SCSI_GET_ADDRESS           IOCTL_SCSI_GET_ADDRESS
#define EMCPAL_IOCTL_SCSI_RESCAN_BUS            IOCTL_SCSI_RESCAN_BUS
#define EMCPAL_IOCTL_SCSI_GET_DUMP_POINTERS     IOCTL_SCSI_GET_DUMP_POINTERS

#else /* Linux */
#define SCSI_IOCTL_DATA_OUT          0
#define SCSI_IOCTL_DATA_IN           1
#define SCSI_IOCTL_DATA_UNSPECIFIED  2


#define F_ANY_ACCESS           EMCPAL_IOCTL_FILE_ANY_ACCESS
#define F_READ_ACCESS          FILE_READ_ACCESS 
#define F_WRITE_ACCESS         FILE_WRITE_ACCESS

#define MD_BUFFERED            EMCPAL_IOCTL_METHOD_BUFFERED

#define IOCTL_SCSI_BASE        FILE_DEVICE_CONTROLLER
#define IOCTL_STORAGE_BASE     FILE_DEVICE_MASS_STORAGE

#define EMCPAL_IOCTL_STORAGE_QUERY_PROPERTY    EMCPAL_IOCTL_CTL_CODE(IOCTL_STORAGE_BASE, 0x0299, MD_BUFFERED, F_READ_ACCESS)
#define EMCPAL_IOCTL_SCSI_PASS_THROUGH         EMCPAL_IOCTL_CTL_CODE(IOCTL_SCSI_BASE, 0x0401, MD_BUFFERED, F_READ_ACCESS | F_WRITE_ACCESS)
#define EMCPAL_IOCTL_SCSI_MINIPORT             EMCPAL_IOCTL_CTL_CODE(IOCTL_SCSI_BASE, 0x0402, MD_BUFFERED, F_READ_ACCESS | F_WRITE_ACCESS)
#define EMCPAL_IOCTL_SCSI_GET_INQUIRY_DATA     EMCPAL_IOCTL_CTL_CODE(IOCTL_SCSI_BASE, 0x0403, MD_BUFFERED, F_ANY_ACCESS)
#define EMCPAL_IOCTL_SCSI_GET_CAPABILITIES     EMCPAL_IOCTL_CTL_CODE(IOCTL_SCSI_BASE, 0x0404, MD_BUFFERED, F_ANY_ACCESS)
#define EMCPAL_IOCTL_SCSI_PASS_THROUGH_DIRECT  EMCPAL_IOCTL_CTL_CODE(IOCTL_SCSI_BASE, 0x0405, MD_BUFFERED, F_READ_ACCESS | F_WRITE_ACCESS)
#define EMCPAL_IOCTL_SCSI_GET_ADDRESS          EMCPAL_IOCTL_CTL_CODE(IOCTL_SCSI_BASE, 0x0406, MD_BUFFERED, F_ANY_ACCESS)
#define EMCPAL_IOCTL_SCSI_RESCAN_BUS           EMCPAL_IOCTL_CTL_CODE(IOCTL_SCSI_BASE, 0x0407, MD_BUFFERED, F_ANY_ACCESS)
#define EMCPAL_IOCTL_SCSI_GET_DUMP_POINTERS    EMCPAL_IOCTL_CTL_CODE(IOCTL_SCSI_BASE, 0x0408, MD_BUFFERED, F_ANY_ACCESS)

/*+++++++++++++++++++++++++++++++++ End SCSI IOCTL +++++++++++++++++++++++++++++++++++++++*/
#endif

#endif /* _EMCPAL_IOCTL_H_ */
