//***************************************************************************
// Copyright (C) EMC Corporation 2007-2009
// All rights reserved.
// Licensed material -- property of EMC Corporation
//**************************************************************************/

//++
// File Name:
//      familyfruid.h
//
// Contents:
//      This file contains all of the Family and FRU IDs.
//
//      The values of the enums in this file are pulled from the resume prom 
//      spec (Windchill 009-002-140). They must remain consistent with the 
//      values in that document and should not be changed otherwise.
//
// Revision History:
//      07/05/07    Joe Ash         Created.
//      08/14/07    Phil Leef       Correcting endian-ness of #defines, such that
//                                  the data returned from Resume PROMs in (little endian format)
//                                  can be appropriately interrpretted, via byte swapping. 
//
// Note: The Family / FRU ID table has moved! It is now located under: 999-998-522.
// Updated to Revision: 999-998-522 A91
//
// AND IT MOVED AGAIN, now its in propel, 999-998-782
// Updated to Revision: 999-998-782 59
//
//--
#ifndef _FAMILY_FRU_ID_H_
#define _FAMILY_FRU_ID_H_

// Resume PROM Family IDs
// these values are from the resume prom spec, do not change
typedef enum _FAMILY_ID {   NO_FAMILY               =0x0000,
                            HAMMERHEAD_FAMILY       =0x0100,
                            SJHAMMER_FAMILY         =0x0200,
                            BIGFOOT_FAMILY          =0x0300,
                            BLACK_WIDOW_FAMILY      =0x0400,
                            IO_MODULE_FAMILY        =0x0500,
                            MAMBA_FAMILY            =0x0600,
                            WILDCATS_FAMILY         =0x0700,
                            MIDPLANE_FAMILY         =0x0800,
                            WILDCATN_FAMILY         =0x0A00,
                            POWER_SUPPLY_FAMILY     =0x0B00,
                            DEBUG_FAMILY            =0x0C00,
                            LCC_FAMILY              =0x0D00,
                            BBU_SPS_UPS_FAMILY      =0x0E00,
                            MAGNUM_FAMILY           =0x0F00,
                            DAUGHTER_CARD_FAMILY    =0x1000,
                            COOLING_MODULE_FAMILY   =0x1100,
                            ARGONAUT_FAMILY         =0x1200,
                            SENTRY_FAMILY           =0x1300,
                            EVERGREEN_FAMILY        =0x1400,
                            INTREPID_FAMILY         =0x1500,
                            STARSCREAM_FAMILY       =0x1600,
                            MEGATRON_FAMILY         =0x1700,
                            DEVASTATOR_FAMILY       =0x1800,
                            BEACHCOMBER_FAMILY      =0x1900,
                            JETFIRE_FAMILY          =0x1A00,
                            SKYDIVE_FAMILY          =0x1C00,
                            MGMT_MODULE_FAMILY      =0x1D00,
                            SILVERBOLT_FAMILY       =0x1E00,
                            STARDUST_FAMILY         =0x1F00,
                            TRITON_FAMILY           =0x2000,
                            DEIMOS_FAMILY           =0x2100,
                            EUROPA_FAMILY           =0x2200,
                            SLIC_2_0_FAMILY         =0x2300,
                            HYPERION_FAMILY         =0x2400,
                            OBERON_FAMILY           =0x2500,
                            COLOSSUS_FAMILY         =0x2600,
                            PCIE_IO_MODULE_FAMILY   =0x2700,
                            LUNA_FAMILY             =0x2800,
                            INFINITY_FAMILY         =0x2900,
                            DATA_DOMAIN_FAMILY      =0xDD00,
                            ISILON_FAMILY           =0xDE00,
                            TIGON_FAMILY            =0x3039,
                            // This value is not taken from resume prom.
                            // Meridian family (aka vVNX)
                            MERIDIAN_FAMILY         =0x7F00,
} FAMILY_ID, *PFAMILY_ID;

// Single Board Tester - Don't know who picked it or why!
// - Don't include in FAMILY_ID enum
#define SBT_FAMILY 0x0609

// The personality module is for the specific module to give more granularity.
// The order and enum ID must not change, they are specified in the resume
// prom spec!
typedef enum _HW_MODULE_TYPE
             {  NO_MODULE                           =0,

                WILDFIRE_NO_PLX                     =(HAMMERHEAD_FAMILY<<16)|0x0100,
                WILDFIRE_PLX                        =(HAMMERHEAD_FAMILY<<16)|0x0200,
                TSUNAMI                             =(HAMMERHEAD_FAMILY<<16)|0x0300,
                BLIZZARD                            =(HAMMERHEAD_FAMILY<<16)|0x0400,
                HURRICANE                           =(HAMMERHEAD_FAMILY<<16)|0x0500,
                MUDSLIDE                            =(HAMMERHEAD_FAMILY<<16)|0x0600,
                TWISTER_B11                         =(HAMMERHEAD_FAMILY<<16)|0x0700,
                IO_ANNEX_NETERION_10GB              =(HAMMERHEAD_FAMILY<<16)|0x0800,
                MGMT                                =(HAMMERHEAD_FAMILY<<16)|0x0900,
                AVALANCHE                           =(HAMMERHEAD_FAMILY<<16)|0x0A00,
                TYPHOON                             =(HAMMERHEAD_FAMILY<<16)|0x0B00,
                ISCSI_MONSOON                       =(HAMMERHEAD_FAMILY<<16)|0x0C00,
                LIGHTNING_CACHE_CARD                =(HAMMERHEAD_FAMILY<<16)|0x0D00,
                TWISTER_B12                         =(HAMMERHEAD_FAMILY<<16)|0x0E00,
                TWISTER_C11                         =(HAMMERHEAD_FAMILY<<16)|0x0F00,
                TWISTER_C12                         =(HAMMERHEAD_FAMILY<<16)|0x1000,
                TWISTER_T2_12                       =(HAMMERHEAD_FAMILY<<16)|0x1100,
                TWISTER_T2_11                       =(HAMMERHEAD_FAMILY<<16)|0x1200,
                WILDFIRE4_PLX                       =(HAMMERHEAD_FAMILY<<16)|0x1300,
                ARTESYN_AC_PS                       =(HAMMERHEAD_FAMILY<<16)|0x1400,
                ARTESYN_DC_PS                       =(HAMMERHEAD_FAMILY<<16)|0x1500,

                // these values are from the resume prom spec, do not change

                SCORPION_DUAL_REV_A                 =(SJHAMMER_FAMILY<<16)|0x0100,
                SCORPION_UNI_REV_A                  =(SJHAMMER_FAMILY<<16)|0x0200,
                SCREWDRIVER                         =(SJHAMMER_FAMILY<<16)|0x0300,
                O_SCREWDRIVER                       =(SJHAMMER_FAMILY<<16)|0x0400,
                FOGCUTTER_DUAL                      =(SJHAMMER_FAMILY<<16)|0x0500,
                FOGCUTTER_PERF                      =(SJHAMMER_FAMILY<<16)|0x0600,
                FOGCUTTER_QUAD                      =(SJHAMMER_FAMILY<<16)|0x0700,
                HEADHUNTER                          =(SJHAMMER_FAMILY<<16)|0x0800,
                FOGCUTTER_II                        =(SJHAMMER_FAMILY<<16)|0x0900,
                SCORPION_DUAL_REV_B                 =(SJHAMMER_FAMILY<<16)|0x0A00,
                SCORPION_UNI_REV_B                  =(SJHAMMER_FAMILY<<16)|0x0B00,
                SCORPION_DUAL_REV_C                 =(SJHAMMER_FAMILY<<16)|0x0C00,
                SCORPION_UNI_REV_C                  =(SJHAMMER_FAMILY<<16)|0x0D00,
                SCORPION_DUAL_REV_D                 =(SJHAMMER_FAMILY<<16)|0x0E00,
                SCORPION_UNI_REV_D                  =(SJHAMMER_FAMILY<<16)|0x0F00,
                SCORPION_UNI_REV_C_NAS              =(SJHAMMER_FAMILY<<16)|0x1000,
                SCORPION_UNI_REV_C_TH               =(SJHAMMER_FAMILY<<16)|0x1100,
                MOJITO                              =(SJHAMMER_FAMILY<<16)|0x1200,

                // these values are from the resume prom spec, do not change

                SULLEY                              =(BIGFOOT_FAMILY<<16)|0x0100,
                YETI_SP                             =(BIGFOOT_FAMILY<<16)|0x0200,
                BOO_ISCSI                           =(BIGFOOT_FAMILY<<16)|0x0300,
                ROZ_FC                              =(BIGFOOT_FAMILY<<16)|0x0400,

                TRIDENT_SP_REV_A                    =(BLACK_WIDOW_FAMILY<<16)|0x0100,
                IRONCLAD_SP_REV_A                   =(BLACK_WIDOW_FAMILY<<16)|0x0200,
                AKULA_SAN_MGMT                      =(BLACK_WIDOW_FAMILY<<16)|0x0500,
                NIMITZ_NAS_MGMT                     =(BLACK_WIDOW_FAMILY<<16)|0x0600,
                TRIDENT_SP_REV_B                    =(BLACK_WIDOW_FAMILY<<16)|0x0700,
                IRONCLAD_SP_REV_B                   =(BLACK_WIDOW_FAMILY<<16)|0x0800,
                TRIDENT_SP_REV_C                    =(BLACK_WIDOW_FAMILY<<16)|0x0900,
                IRONCLAD_SP_REV_C                   =(BLACK_WIDOW_FAMILY<<16)|0x0A00,
                CAS_BRICK_REV_C                     =(BLACK_WIDOW_FAMILY<<16)|0x0B00,
                NAUTILUS_SP_REV_C                   =(BLACK_WIDOW_FAMILY<<16)|0x0C00,
                NAUTILUS_IRONCLAD_REV_C_SPARE       =(BLACK_WIDOW_FAMILY<<16)|0x0D00,
                TRIDENT_REV_C_SPARE                 =(BLACK_WIDOW_FAMILY<<16)|0x0E00,
                AKULA_SAN_MGMT_W_USB                =(BLACK_WIDOW_FAMILY<<16)|0x0F00,

                // these values are from the resume prom spec, do not change

                TOMAHAWK                            =(IO_MODULE_FAMILY<<16)|0x0100,
                HARPOON                             =(IO_MODULE_FAMILY<<16)|0x0200,
                THUNDERBOLT                         =(IO_MODULE_FAMILY<<16)|0x0300,
                THUNDERCHILD                        =(IO_MODULE_FAMILY<<16)|0x0400,
                SIB_DOUBLEWIDE                      =(IO_MODULE_FAMILY<<16)|0x0500,
                SANDSTORM                           =(IO_MODULE_FAMILY<<16)|0x0600,
                QUICKSAND                           =(IO_MODULE_FAMILY<<16)|0x0700,
                COROMANDEL                          =(IO_MODULE_FAMILY<<16)|0x0800,
                POLARIS_OPTICAL                     =(IO_MODULE_FAMILY<<16)|0x0900,
                POLARIS_COPPER                      =(IO_MODULE_FAMILY<<16)|0x0A00,
                FIRESTORM                           =(IO_MODULE_FAMILY<<16)|0x0B00,
                POSEIDON_OPTICAL_1PORT              =(IO_MODULE_FAMILY<<16)|0x0C00,
                POSEIDON_OPTICAL_2PORT              =(IO_MODULE_FAMILY<<16)|0x0D00,
                POSEIDON_COPPER_1PORT               =(IO_MODULE_FAMILY<<16)|0x0E00,
                POSEIDON_COPPER_2PORT               =(IO_MODULE_FAMILY<<16)|0x0F00,
                TOMAHAWK_C6                         =(IO_MODULE_FAMILY<<16)|0x1000,
                SPARTAN                             =(IO_MODULE_FAMILY<<16)|0x1100,
                SPARTAN_PLUS                        =(IO_MODULE_FAMILY<<16)|0x1200,
                BLACKICE                            =(IO_MODULE_FAMILY<<16)|0x1300,
                GLACIER                             =(IO_MODULE_FAMILY<<16)|0x1400,
                GLACIER_PLUS                        =(IO_MODULE_FAMILY<<16)|0x1500,
                SNOWSTORM                           =(IO_MODULE_FAMILY<<16)|0x1600,
                HORNET_BASEBOARD                    =(IO_MODULE_FAMILY<<16)|0x1700,
                HORNET_1GB_WO_BBU                   =(IO_MODULE_FAMILY<<16)|0x1800,
                HORNET_1GB_W_BBU                    =(IO_MODULE_FAMILY<<16)|0x1900,
                HORNET_2GB_WO_BBU                   =(IO_MODULE_FAMILY<<16)|0x1A00,
                HORNET_2GB_W_BBU                    =(IO_MODULE_FAMILY<<16)|0x1B00,
                POSEIDON_OPTICAL_1PORT_REV_B        =(IO_MODULE_FAMILY<<16)|0x1C00,
                POSEIDON_OPTICAL_2PORT_REV_B        =(IO_MODULE_FAMILY<<16)|0x1D00,
                HEATWAVE                            =(IO_MODULE_FAMILY<<16)|0x1E00,
                GLACIER_REV_C                       =(IO_MODULE_FAMILY<<16)|0x1F00,
                SUPERCELL                           =(IO_MODULE_FAMILY<<16)|0x2000,
                POSEIDON_OPTICAL_2PORT_REV_B1       =(IO_MODULE_FAMILY<<16)|0x2100,
                SCYLLA_DOUBLEWIDE                   =(IO_MODULE_FAMILY<<16)|0x2200,
                SAIPAN_SATA_DRIVE                   =(IO_MODULE_FAMILY<<16)|0x2300,
                ERUPTION_COPPER_2PORT               =(IO_MODULE_FAMILY<<16)|0x2400,
                HYPERNOVA                           =(IO_MODULE_FAMILY<<16)|0x2500,
                MOONQUAKE                           =(IO_MODULE_FAMILY<<16)|0x2600,
                GLACTAN                             =(IO_MODULE_FAMILY<<16)|0x2700,
                POSEIDON_II_OPTICAL_2PORT           =(IO_MODULE_FAMILY<<16)|0x2800,
                COLDFRONT                           =(IO_MODULE_FAMILY<<16)|0x2900,
                AURORA                              =(IO_MODULE_FAMILY<<16)|0x2A00,
                ERUPTION_COPPER_2PORT_REV_B         =(IO_MODULE_FAMILY<<16)|0x2B00,
                SCYLLA2_DOUBLEWIDE                  =(IO_MODULE_FAMILY<<16)|0x2C00,
                AURORA_II                           =(IO_MODULE_FAMILY<<16)|0x2D00,
                ELNINO                              =(IO_MODULE_FAMILY<<16)|0x2E00,
                LAVAFLOW                            =(IO_MODULE_FAMILY<<16)|0x2F00,
                ERUPTION_2PORT_REV_C_84823          =(IO_MODULE_FAMILY<<16)|0x3000,
                ERUPTION_2PORT_REV_C_84833          =(IO_MODULE_FAMILY<<16)|0x3100,
                MOONSHADOW                          =(IO_MODULE_FAMILY<<16)|0x3200,
                MOONSHINE                           =(IO_MODULE_FAMILY<<16)|0x3300,
                CHIMERA                             =(IO_MODULE_FAMILY<<16)|0x3400,
                VORTEX16                            =(IO_MODULE_FAMILY<<16)|0x3500,
                VORTEX10                            =(IO_MODULE_FAMILY<<16)|0x3600,
                ICEBERG_2GB_W_BBU                   =(IO_MODULE_FAMILY<<16)|0x3700,
                ICEBERG_4GB_W_BBU                   =(IO_MODULE_FAMILY<<16)|0x3800,
                ICEBERG_8GB_W_BBU                   =(IO_MODULE_FAMILY<<16)|0x3900,
                RAINSTORM                           =(IO_MODULE_FAMILY<<16)|0x3A00,
                ICEBERG_II_2GB_W_BBU                =(IO_MODULE_FAMILY<<16)|0x3B00,
                ICEBERG_II_4GB_W_BBU                =(IO_MODULE_FAMILY<<16)|0x3C00,
                ICEBERG_II_8GB_W_BBU                =(IO_MODULE_FAMILY<<16)|0x3D00,
                LANDSLIDE                           =(IO_MODULE_FAMILY<<16)|0x3E00,
                CHIMERA_GEN_3_QDR                   =(IO_MODULE_FAMILY<<16)|0x3F00,
                CHIMERA_GEN_3_FDR                   =(IO_MODULE_FAMILY<<16)|0x4000,
                MOONLITE                            =(IO_MODULE_FAMILY<<16)|0x4100,
                ROCKSLIDE                           =(IO_MODULE_FAMILY<<16)|0x4200,
                ERUPTION_REV_D                      =(IO_MODULE_FAMILY<<16)|0x4300,
                ELNINO_REV_B                        =(IO_MODULE_FAMILY<<16)|0x4400,
                BLAZAR                              =(IO_MODULE_FAMILY<<16)|0x4500,
                VORTEX16Q                           =(IO_MODULE_FAMILY<<16)|0x4600,
                RAINSTORM_2PORT                     =(IO_MODULE_FAMILY<<16)|0x4700,
                DOWNBURST                           =(IO_MODULE_FAMILY<<16)|0x4800,
                WINDSTORM                           =(IO_MODULE_FAMILY<<16)|0x4900,
                SEADOG                              =(IO_MODULE_FAMILY<<16)|0x5000,
                ASTEROID                            =(IO_MODULE_FAMILY<<16)|0x5100,
                ICEBERG_2GB_FREY_B2_W_BBU           =(IO_MODULE_FAMILY<<16)|0x5200,
                ICEBERG_4GB_FREY_B2_W_BBU           =(IO_MODULE_FAMILY<<16)|0x5300,
                ICEBERG_8GB_FREY_B2_W_BBU           =(IO_MODULE_FAMILY<<16)|0x5400,
                WHIRLWIND_700GB                     =(IO_MODULE_FAMILY<<16)|0x5500,
                WHIRLWIND_350GB                     =(IO_MODULE_FAMILY<<16)|0x5600,
                WHIRLWIND_175GB                     =(IO_MODULE_FAMILY<<16)|0x5700,
                GORGON                              =(IO_MODULE_FAMILY<<16)|0x5800,
                GORGON_X16                          =(IO_MODULE_FAMILY<<16)|0x5900,
                PHOENIX_2GB                         =(IO_MODULE_FAMILY<<16)|0x5A00,
                PHOENIX_4GB                         =(IO_MODULE_FAMILY<<16)|0x5B00,
                RAINSTORM_E                         =(IO_MODULE_FAMILY<<16)|0x5C00,
                RAINFALL                            =(IO_MODULE_FAMILY<<16)|0x5D00,
                PLUTO                               =(IO_MODULE_FAMILY<<16)|0x5E00,
                ROCKSLIDE_W_B1_MAC                  =(IO_MODULE_FAMILY<<16)|0x5F00,
                LANDSLIDE_W_B1_MAC                  =(IO_MODULE_FAMILY<<16)|0x6000,
                WHIRLWIND_1400GB                    =(IO_MODULE_FAMILY<<16)|0x6100,
                DELUGE                              =(IO_MODULE_FAMILY<<16)|0x6200,
                DUSTDEVIL                           =(IO_MODULE_FAMILY<<16)|0x6300,
                SNOWDEVIL                           =(IO_MODULE_FAMILY<<16)|0x6400,
                MAELSTROM                           =(IO_MODULE_FAMILY<<16)|0x6500,
                DOWNPOUR                            =(IO_MODULE_FAMILY<<16)|0x6600,
                RAINFALL_W_THERMAL_SENSOR           =(IO_MODULE_FAMILY<<16)|0x6700,
                HERRA_W_NVDIMM                      =(IO_MODULE_FAMILY<<16)|0x6800,
                HERRA_W_RDIMM                       =(IO_MODULE_FAMILY<<16)|0x6900,
                MOONSHADOW_C2                       =(IO_MODULE_FAMILY<<16)|0x6A00,
                MOONLITE_C2                         =(IO_MODULE_FAMILY<<16)|0x6B00,
                CALYPSO_DD_NVRAM                    =(IO_MODULE_FAMILY<<16)|0X6C00,
                // When adding new IO Modules, also increment MAX_SLIC_COUNT
                // and add the new module to SPID (SpidInitSupportedIoModules).

                // these values are from the resume prom spec, do not change

                BOOMSLANG_SP_REV_A                  =(MAMBA_FAMILY<<16)|0x0100,
                MAMBA_PSU_AC                        =(MAMBA_FAMILY<<16)|0x0200,
                MAMBA_PSU_DC                        =(MAMBA_FAMILY<<16)|0x0300,
                COBRA                               =(MAMBA_FAMILY<<16)|0x0400,
                MAMBA_PSU_AC_2ND                    =(MAMBA_FAMILY<<16)|0x0500,
                MAMBA_IO_ISCSI                      =(MAMBA_FAMILY<<16)|0x0600,
                MAMBA_IO_FC                         =(MAMBA_FAMILY<<16)|0x0700,
                TAIPAN                              =(MAMBA_FAMILY<<16)|0x0800,
                MAMBA_TEST_MIDPLANE                 =(MAMBA_FAMILY<<16)|0x0900,
                MAMBA_BOA                           =(MAMBA_FAMILY<<16)|0x0A00,
                MAMBA_BOA_C6                        =(MAMBA_FAMILY<<16)|0x0B00,

                WILDCATS_SP_REV_A                   =(WILDCATS_FAMILY<<16)|0x0200,
                WILDCATS_SP_REV_B                   =(WILDCATS_FAMILY<<16)|0x0300,
                WILDCATS_SP_REV_C                   =(WILDCATS_FAMILY<<16)|0x0400,
                WILDCATS_VE_SP                      =(WILDCATS_FAMILY<<16)|0x0500,
                SOLAR_FLARE                         =(WILDCATS_FAMILY<<16)|0x0700,
                EARTHQUAKE                          =(WILDCATS_FAMILY<<16)|0x0800,
                TORNADO_ANNEX                       =(WILDCATS_FAMILY<<16)|0x0900,
                MESOCYCLONE                         =(WILDCATS_FAMILY<<16)|0x0A00,
                CATNIP                              =(WILDCATS_FAMILY<<16)|0x0B00,
                SOLAR_FLARE_LF                      =(WILDCATS_FAMILY<<16)|0x0C00,

                // these values are from the resume prom spec, do not change

                FOGBOW                              =(MIDPLANE_FAMILY<<16)|0x0100,
                BROADSIDE                           =(MIDPLANE_FAMILY<<16)|0x0200,
                STILETTO                            =(MIDPLANE_FAMILY<<16)|0x0300,
                D15                                 =(MIDPLANE_FAMILY<<16)|0x0400,
                BULLET                              =(MIDPLANE_FAMILY<<16)|0x0500,
                BROADSIDE_GEN_2                     =(MIDPLANE_FAMILY<<16)|0x0600,
                HOLSTER                             =(MIDPLANE_FAMILY<<16)|0x0700,
                DERRINGER                           =(MIDPLANE_FAMILY<<16)|0x0800,
                VIPER                               =(MIDPLANE_FAMILY<<16)|0x0900,
                D15LF                               =(MIDPLANE_FAMILY<<16)|0x0A00,
                CITADEL                             =(MIDPLANE_FAMILY<<16)|0x0B00,
                FOGBOW_2                            =(MIDPLANE_FAMILY<<16)|0x0C00,
                BOXWOOD                             =(MIDPLANE_FAMILY<<16)|0x0D00,
                KNOT                                =(MIDPLANE_FAMILY<<16)|0X0E00,
                TOLEDO                              =(MIDPLANE_FAMILY<<16)|0X0F00,
                BUNKER                              =(MIDPLANE_FAMILY<<16)|0x1000,
                VOYAGER                             =(MIDPLANE_FAMILY<<16)|0X1100,
                SEA_TOWER                           =(MIDPLANE_FAMILY<<16)|0X1200,
                SIDESWIPE                           =(MIDPLANE_FAMILY<<16)|0X1300,
                BOXWOOD_HF                          =(MIDPLANE_FAMILY<<16)|0X1400,
                KNOT_HF                             =(MIDPLANE_FAMILY<<16)|0X1500,
                RATCHET                             =(MIDPLANE_FAMILY<<16)|0X1600,
                VIKING                              =(MIDPLANE_FAMILY<<16)|0X1700,
                VANGUARD                            =(MIDPLANE_FAMILY<<16)|0X1800,
                FALLBACK                            =(MIDPLANE_FAMILY<<16)|0X1900,
                PUNCH                               =(MIDPLANE_FAMILY<<16)|0X1A00,
                STRATOSPHERE                        =(MIDPLANE_FAMILY<<16)|0X1B00,
                SKYDIVE_12                          =(MIDPLANE_FAMILY<<16)|0X1C00,
                SKYDIVE_25                          =(MIDPLANE_FAMILY<<16)|0X1D00,
                SIDESWIPE_REV_C                     =(MIDPLANE_FAMILY<<16)|0X1E00,
                FIRETOWER                           =(MIDPLANE_FAMILY<<16)|0X1F00,
                STARDUST                            =(MIDPLANE_FAMILY<<16)|0X2000,
                BARRICADE                           =(MIDPLANE_FAMILY<<16)|0X2100,
                FALLBACK_872MP                      =(MIDPLANE_FAMILY<<16)|0X2200,
                RAMHORN                             =(MIDPLANE_FAMILY<<16)|0X2300,
                STEELJAW                            =(MIDPLANE_FAMILY<<16)|0X2400,
                CAYENNE                             =(MIDPLANE_FAMILY<<16)|0X2500,
                ANCHO                               =(MIDPLANE_FAMILY<<16)|0X2600,
                TABASCO                             =(MIDPLANE_FAMILY<<16)|0X2700,
                PROTEUS                             =(MIDPLANE_FAMILY<<16)|0X2800,
                DEIMOS                              =(MIDPLANE_FAMILY<<16)|0X2900,
                DEIMOS_REV_C                        =(MIDPLANE_FAMILY<<16)|0X2A00,
                DEIMOS_X8                           =(MIDPLANE_FAMILY<<16)|0X3000,
                NAGA                                =(MIDPLANE_FAMILY<<16)|0X3100,
                EUROPA_2U                           =(MIDPLANE_FAMILY<<16)|0X3200,
                MIRANDA                             =(MIDPLANE_FAMILY<<16)|0X3300,
                RHEA                                =(MIDPLANE_FAMILY<<16)|0X3400,
                TELESTO                             =(MIDPLANE_FAMILY<<16)|0X3500,
                SINOPE                              =(MIDPLANE_FAMILY<<16)|0X3600,
                CALYPSO                             =(MIDPLANE_FAMILY<<16)|0X3700,
                COLOSSUS                            =(MIDPLANE_FAMILY<<16)|0X3800,
                WATCHTOWER                          =(MIDPLANE_FAMILY<<16)|0X3900,
                VERONA                              =(MIDPLANE_FAMILY<<16)|0X3A00,
                SINOPE_REV_B                        =(MIDPLANE_FAMILY<<16)|0X3B00,
                CALYPSO_REV_B                       =(MIDPLANE_FAMILY<<16)|0X3C00,
                EUROPA_1U                           =(MIDPLANE_FAMILY<<16)|0X3D00,
                NAGA_80                             =(MIDPLANE_FAMILY<<16)|0X3E00,
                WRAITH                              =(MIDPLANE_FAMILY<<16)|0X3F00,
                CORTANA                             =(MIDPLANE_FAMILY<<16)|0X4000,
                // This value is not taken from resume prom
                // Used by vVNX product under hypervisor (or baremetal?)
                MERIDIAN                            =(MIDPLANE_FAMILY<<16)|0XFF11,

                WILDCATN_SP_REV_A                   =(WILDCATN_FAMILY<<16)|0x0100,
                HAILSTORM                           =(WILDCATN_FAMILY<<16)|0x0200,
                HURRICANEII                         =(WILDCATN_FAMILY<<16)|0x0300,
                WILDCATN_SP_REV_B                   =(WILDCATN_FAMILY<<16)|0x0400,
                WILDCATN_SP_REV_C                   =(WILDCATN_FAMILY<<16)|0x0500,

                // these values are from the resume prom spec, do not change

                AC_ASTEC_TANKER                     =(POWER_SUPPLY_FAMILY<<16)|0x0100,
                AC_ACBEL_TANKER                     =(POWER_SUPPLY_FAMILY<<16)|0x0200,
                DC_ASTEC_TANKER                     =(POWER_SUPPLY_FAMILY<<16)|0x0300,
                FAKE_TANKER                         =(POWER_SUPPLY_FAMILY<<16)|0x0400,
                AC_POWERONE_ANNA_MARIA              =(POWER_SUPPLY_FAMILY<<16)|0x0500,
                DC_POWERONE_ANNA_MARIA              =(POWER_SUPPLY_FAMILY<<16)|0x0600,
                AC_ASTEC_TANKER_II                  =(POWER_SUPPLY_FAMILY<<16)|0x0700,
                DC_ACBEL_STILETTO                   =(POWER_SUPPLY_FAMILY<<16)|0x0800,
                AC_ASTEC_D15                        =(POWER_SUPPLY_FAMILY<<16)|0x0900,
                BULLET_BLOWER_MODULE                =(POWER_SUPPLY_FAMILY<<16)|0x0A00,
                AC_POWERONE_SARA_GEN2               =(POWER_SUPPLY_FAMILY<<16)|0x0B00,
                DC_POWERONE_SARA_GEN2               =(POWER_SUPPLY_FAMILY<<16)|0x0C00,
                AC_ASTEC_MAGNUM                     =(POWER_SUPPLY_FAMILY<<16)|0x0D00,
                AC_ACBEL_MAGNUM                     =(POWER_SUPPLY_FAMILY<<16)|0x0E00,
                AC_ASTEC_SARA_GEN2                  =(POWER_SUPPLY_FAMILY<<16)|0x0F00,
                AC_ACBEL_STILETTO                   =(POWER_SUPPLY_FAMILY<<16)|0x1000,
                AC_ACBEL_DERRINGER                  =(POWER_SUPPLY_FAMILY<<16)|0x1100,
                DC_ACBEL_DERRINGER                  =(POWER_SUPPLY_FAMILY<<16)|0x1200,
                AC_EMERSON_MAGNUM_GEN2              =(POWER_SUPPLY_FAMILY<<16)|0x1300,
                AC_ACBEL_SENTRY_GEN2                =(POWER_SUPPLY_FAMILY<<16)|0x1400,
                AC_ACBEL_DAE_GEN3                   =(POWER_SUPPLY_FAMILY<<16)|0x1500,
                AC_EMERSON_DAE_GEN3                 =(POWER_SUPPLY_FAMILY<<16)|0x1600,
                AC_EMERSON_MAGNUM                   =(POWER_SUPPLY_FAMILY<<16)|0x1700,
                ACBEL_DERRINGER_BLOWER_MODULE       =(POWER_SUPPLY_FAMILY<<16)|0x1800,
                AC_ACBEL_DERRINGER_071              =(POWER_SUPPLY_FAMILY<<16)|0x1900,
                HVDC_ACBEL_DERRINGER                =(POWER_SUPPLY_FAMILY<<16)|0x1A00,
                AC_ACBEL_TANKER_ADAPT_COOL          =(POWER_SUPPLY_FAMILY<<16)|0x1B00,
                AC_DC_JUNIPER                       =(POWER_SUPPLY_FAMILY<<16)|0x1C00,
                AC_DC_EMERSON_ARGONAUT              =(POWER_SUPPLY_FAMILY<<16)|0x1D00,
                DC_ACBEL_SENTRY                     =(POWER_SUPPLY_FAMILY<<16)|0x1E00,
                AC_DC_ACBEL_SUPERTANKER             =(POWER_SUPPLY_FAMILY<<16)|0x1F00,
                AC_ACBEL_VOYAGER                    =(POWER_SUPPLY_FAMILY<<16)|0x2000,
                AC_ACBEL_JUNIPER                    =(POWER_SUPPLY_FAMILY<<16)|0x2100,
                AC_ACBEL_ARGONAUT                   =(POWER_SUPPLY_FAMILY<<16)|0x2200,
                EMERSON_SUPERTANKER                 =(POWER_SUPPLY_FAMILY<<16)|0x2300,
                AC_EMERSON_SENTRY                   =(POWER_SUPPLY_FAMILY<<16)|0x2400,
                DERRINGER_EMERSON                   =(POWER_SUPPLY_FAMILY<<16)|0x2500,
                VOYAGER_EMERSON                     =(POWER_SUPPLY_FAMILY<<16)|0x2600,
                ACBEL_3GEN_VE_DAE                   =(POWER_SUPPLY_FAMILY<<16)|0x2700,
                EMERSON_3GEN_VE_DAE                 =(POWER_SUPPLY_FAMILY<<16)|0x2800,
                AC_ACBEL_OCTANE                     =(POWER_SUPPLY_FAMILY<<16)|0x2900,
                AC_ACBEL_BLASTOFF                   =(POWER_SUPPLY_FAMILY<<16)|0x2A00,
                AC_ACBEL_RAMJET                     =(POWER_SUPPLY_FAMILY<<16)|0x2B00,
                SUPERCAPACITOR_120                  =(POWER_SUPPLY_FAMILY<<16)|0x2C00,
                SUPERCAPACITOR_1500                 =(POWER_SUPPLY_FAMILY<<16)|0x2D00,
                DAE_AC_1600                         =(POWER_SUPPLY_FAMILY<<16)|0x2E00,
                DAE_AC_1080                         =(POWER_SUPPLY_FAMILY<<16)|0x2F00,
                DC_JUNIPER_700                      =(POWER_SUPPLY_FAMILY<<16)|0x3000,
                AC_OPTIMUS                          =(POWER_SUPPLY_FAMILY<<16)|0x3100,
                DC_ACBEL_BLASTOFF                   =(POWER_SUPPLY_FAMILY<<16)|0x3200,
                AC_JUNO_2                           =(POWER_SUPPLY_FAMILY<<16)|0x3300,
                AC_FLEXPOWER_BLASTOFF               =(POWER_SUPPLY_FAMILY<<16)|0x3400,
                TABASCO_PS_COOLING_MODULE           =(POWER_SUPPLY_FAMILY<<16)|0x3500,
                AC_FLEXPOWER_OPTIMUS                =(POWER_SUPPLY_FAMILY<<16)|0x3600,
                AC_EMERSON_RAMJET                   =(POWER_SUPPLY_FAMILY<<16)|0x3700,
                DC_TABASCO_PS_COOLING_MODULE        =(POWER_SUPPLY_FAMILY<<16)|0x3800,
                AC_FLEXPOWER_RAMJET                 =(POWER_SUPPLY_FAMILY<<16)|0x3900,
                AC_ACBEL_RAMJET_197                 =(POWER_SUPPLY_FAMILY<<16)|0x3A00,
                AC_ACBEL_GALVATRON                  =(POWER_SUPPLY_FAMILY<<16)|0x3B00,
                AC_FLEXPOWER_GALVATRON              =(POWER_SUPPLY_FAMILY<<16)|0x3C00,
                AC_ARTESYN_GALVATRON                =(POWER_SUPPLY_FAMILY<<16)|0x3D00,
                AC_FLEXPOWER_OPTIMUS_GEN_1_PLUS     =(POWER_SUPPLY_FAMILY<<16)|0x3E00,
                AC_ACBEL_OPTIMUS_GEN_1_PLUS         =(POWER_SUPPLY_FAMILY<<16)|0x3F00,
                DC_ACBEL_BLASTOFF_GEN_1_PLUS        =(POWER_SUPPLY_FAMILY<<16)|0x4000,
                AC_ACBEL_OPTIMUS_GEN_1_PLUS_611     =(POWER_SUPPLY_FAMILY<<16)|0x4100,
                AC_ACBEL_OPTIMUS_GEN_2              =(POWER_SUPPLY_FAMILY<<16)|0x4200,
                AC_FLEXPOWER_OPTIMUS_GEN_2          =(POWER_SUPPLY_FAMILY<<16)|0x4300,
                AC_ARTESYN_OPTIMUS_GEN_2            =(POWER_SUPPLY_FAMILY<<16)|0x4400,
                AC_ACBEL_RAMJET_GEN_2               =(POWER_SUPPLY_FAMILY<<16)|0x4500,
                AC_FLEXPOWER_RAMJET_GEN_2           =(POWER_SUPPLY_FAMILY<<16)|0x4600,
                AC_ARTESYN_RAMJET_GEN_2             =(POWER_SUPPLY_FAMILY<<16)|0x4700,
                AC_ACBEL_ZEUS_GEN_2                 =(POWER_SUPPLY_FAMILY<<16)|0x4800,
                AC_FLEXPOWER_ZEUS_GEN_2             =(POWER_SUPPLY_FAMILY<<16)|0x4900,
                AC_ARTESYN_ZEUS_GEN_2               =(POWER_SUPPLY_FAMILY<<16)|0x4A00,

                // these values are from the resume prom spec, do not change

                SEACAT                              =(DEBUG_FAMILY<<16)|0x0100,
                SEATIGER                            =(DEBUG_FAMILY<<16)|0x0200,
                SEAGULLX8                           =(DEBUG_FAMILY<<16)|0x0300,
                SUNSTREAKER                         =(DEBUG_FAMILY<<16)|0x0400,
                COSMOS                              =(DEBUG_FAMILY<<16)|0x0500,

                STILETTO_LCC                        =(LCC_FAMILY<<16)|0x0100,
                D15_LCC                             =(LCC_FAMILY<<16)|0x0200,
                BULLET_LCC                          =(LCC_FAMILY<<16)|0x0300,
                DERRINGER_LCC                       =(LCC_FAMILY<<16)|0x0400,
                VIPER_LCC                           =(LCC_FAMILY<<16)|0x0500,
                D15LF_LCC                           =(LCC_FAMILY<<16)|0x0600,
                PINECONE_LCC                        =(LCC_FAMILY<<16)|0X0700,
                VOYAGER_LCC                         =(LCC_FAMILY<<16)|0X0800,
                VOYAGER_ICM                         =(LCC_FAMILY<<16)|0X0900,
                VIKING_LCC                          =(LCC_FAMILY<<16)|0X0A00,
                VIKING_IO_EXP                       =(LCC_FAMILY<<16)|0X0B00,
                VANGUARD_LCC                        =(LCC_FAMILY<<16)|0X0C00,
                VOYAGER_LCC_REV_A                   =(LCC_FAMILY<<16)|0X0D00,
                STARFIRE                            =(LCC_FAMILY<<16)|0X0E00,
                CAYENNE_LCC                         =(LCC_FAMILY<<16)|0X0F00,
                ANCHO_LCC                           =(LCC_FAMILY<<16)|0X1000,
                TABASCO_LCC                         =(LCC_FAMILY<<16)|0X1100,
                NAGA_LCC                            =(LCC_FAMILY<<16)|0X1200,

                MAGNUM_BBU_ACBEL_067                =(BBU_SPS_UPS_FAMILY<<16)|0x0100,
                HORNET_BBU_BEL                      =(BBU_SPS_UPS_FAMILY<<16)|0x0200,
                MAGNUM_BBU_DELTA                    =(BBU_SPS_UPS_FAMILY<<16)|0x0300,
                MAGNUM_BBU_ACBEL_071                =(BBU_SPS_UPS_FAMILY<<16)|0x0400,
                SENTRY_BBU_ACBEL_073                =(BBU_SPS_UPS_FAMILY<<16)|0x0500,
                EVERGREEN_BBU_ACBEL                 =(BBU_SPS_UPS_FAMILY<<16)|0x0600,
                ICEBERG_BBU_BEL                     =(BBU_SPS_UPS_FAMILY<<16)|0x0700,
                LI_ION_SPS_2_2_KW_WITHOUT_BATTERY   =(BBU_SPS_UPS_FAMILY<<16)|0x0800,
                LI_ION_2_42_KW_BATTERY_PACK_082     =(BBU_SPS_UPS_FAMILY<<16)|0x0900,
                COPILOT                             =(BBU_SPS_UPS_FAMILY<<16)|0x0A00,
                ICEBERG_BBU_2_BEL                   =(BBU_SPS_UPS_FAMILY<<16)|0x0B00,
                COPILOT_K2                          =(BBU_SPS_UPS_FAMILY<<16)|0x0C00,
                LI_ION_2_42_KW_BATTERY_PACK_115     =(BBU_SPS_UPS_FAMILY<<16)|0x0D00,
                SENTRY_BBU_ACBEL_PHET               =(BBU_SPS_UPS_FAMILY<<16)|0x0E00,
                EVERGREEN_BBU_ACBEL_PHET            =(BBU_SPS_UPS_FAMILY<<16)|0x0F00,
                COPILOT_A123_SELF_TEST              =(BBU_SPS_UPS_FAMILY<<16)|0x1000,
                COPILOT_K2_SELF_TEST                =(BBU_SPS_UPS_FAMILY<<16)|0x1100,
                SENTRY_BBU_K2                       =(BBU_SPS_UPS_FAMILY<<16)|0x1200,
                EVERGREEN_BBU_K2                    =(BBU_SPS_UPS_FAMILY<<16)|0x1300,
                NAVIGATOR_A123                      =(BBU_SPS_UPS_FAMILY<<16)|0x1400,
                COPILOT_2_0_A123                    =(BBU_SPS_UPS_FAMILY<<16)|0x1500,

                // these values are from the resume prom spec, do not change

                MAGNUM_CPU_REV_A_WITH_SAS           =(MAGNUM_FAMILY<<16)|0x0100,
                MAGNUM_CPU_REV_B_WITH_SAS           =(MAGNUM_FAMILY<<16)|0x0200,
                MAGNUM_CPU_REV_C_WITH_SAS           =(MAGNUM_FAMILY<<16)|0x0300,
                MAGNUM_CPU_REV_D_WITH_SAS           =(MAGNUM_FAMILY<<16)|0x0400,
                MAGNUM_CPU_REV_E_WITH_SAS           =(MAGNUM_FAMILY<<16)|0x0500,
                MAGNUM_CPU_REV_F_WITH_SAS           =(MAGNUM_FAMILY<<16)|0x0600,
                MAGNUM_CPU_REV_A_WITHOUT_SAS        =(MAGNUM_FAMILY<<16)|0x0700,
                MAGNUM_CPU_REV_B_WITHOUT_SAS        =(MAGNUM_FAMILY<<16)|0x0800,
                MAGNUM_CPU_REV_C_WITHOUT_SAS        =(MAGNUM_FAMILY<<16)|0x0900,
                MAGNUM_CPU_REV_D_WITHOUT_SAS        =(MAGNUM_FAMILY<<16)|0x0A00,
                MAGNUM_CPU_REV_E_WITHOUT_SAS        =(MAGNUM_FAMILY<<16)|0x0B00,
                MAGNUM_CPU_REV_F_WITHOUT_SAS        =(MAGNUM_FAMILY<<16)|0x0C00,
                MAGNUM_1CORE_CPU_REV_C_WITH_SAS     =(MAGNUM_FAMILY<<16)|0x0D00,
                MAGNUM_1CORE_CPU_REV_D_WITH_SAS     =(MAGNUM_FAMILY<<16)|0x0E00,
                MAGNUM_1CORE_CPU_REV_E_WITH_SAS     =(MAGNUM_FAMILY<<16)|0x0F00,
                MAGNUM_1CORE_CPU_REV_F_WITH_SAS     =(MAGNUM_FAMILY<<16)|0x1000,

                MUZZLE_WITH_SAS                     =(DAUGHTER_CARD_FAMILY<<16)|0x0100,
                MUZZLE_WITHOUT_SAS                  =(DAUGHTER_CARD_FAMILY<<16)|0x0200,
                PEACEMAKER_WITH_SAS                 =(DAUGHTER_CARD_FAMILY<<16)|0x0300,
                PEACEMAKER_WITHOUT_SAS              =(DAUGHTER_CARD_FAMILY<<16)|0x0400,
                GROWLER                             =(DAUGHTER_CARD_FAMILY<<16)|0x0500,
                PHANTOM                             =(DAUGHTER_CARD_FAMILY<<16)|0x0600,
                GROWLER_DVT                         =(DAUGHTER_CARD_FAMILY<<16)|0x0700,
                VIKING_SYSTEM_STATUS_CARD           =(DAUGHTER_CARD_FAMILY<<16)|0x0800,
                VIKING_LCC_SUPER_CAP                =(DAUGHTER_CARD_FAMILY<<16)|0x0900,
                NAGA_SYSTEM_STATUS_CARD             =(DAUGHTER_CARD_FAMILY<<16)|0x0A00,

                SILENCER                            =(COOLING_MODULE_FAMILY<<16)|0x0100,
                VOYAGER_FRONT_FAN_COTROL            =(COOLING_MODULE_FAMILY<<16)|0x0200,
                AIRWAVE_COOLING_MODULE              =(COOLING_MODULE_FAMILY<<16)|0x0300,

                // these values are from the resume prom spec, do not change

                ARGONAUT_SP_CPU_2_0_GHZ             =(ARGONAUT_FAMILY<<16)|0x0100,
                ARGONAUT_SP_CPU_2_26_GHZ            =(ARGONAUT_FAMILY<<16)|0x0200,
                ARGONAUT_SP_CPU_2_53_GHZ            =(ARGONAUT_FAMILY<<16)|0x0300,
                ARGONAUT_SP_CPU_2_80_GHZ_NEH        =(ARGONAUT_FAMILY<<16)|0x0400,
                ARGONAUT_SP_CPU_2_93_GHZ_NEH        =(ARGONAUT_FAMILY<<16)|0x0500,
                ARGONAUT_SP_CPU_2_0_GHZ_NEH_REV_B   =(ARGONAUT_FAMILY<<16)|0x0600,
                ARGONAUT_SP_CPU_2_26_GHZ_NEH_REV_B  =(ARGONAUT_FAMILY<<16)|0x0700,
                ARGONAUT_SP_CPU_2_53_GHZ_NEH_REV_B  =(ARGONAUT_FAMILY<<16)|0x0800,
                ARGONAUT_SP_CPU_2_80_GHZ_NEH_REV_B  =(ARGONAUT_FAMILY<<16)|0x0900,
                ARGONAUT_SP_CPU_2_93_GHZ_NEH_REV_B  =(ARGONAUT_FAMILY<<16)|0x0A00,
                ARGONAUT_SP_CPU_2_40_GHZ_WSM_REV_B  =(ARGONAUT_FAMILY<<16)|0x0B00,
                ARGONAUT_SP_CPU_2_80_GHZ_WSM_REV_B  =(ARGONAUT_FAMILY<<16)|0x0C00,
                ARGONAUT_SP_CPU_2_13_GHZ_WSM_REV_B  =(ARGONAUT_FAMILY<<16)|0x0D00,

                SENTRY_SP_2_0_GHZ_GROWLER_0_GB      =(SENTRY_FAMILY<<16)|0x0100,
                SENTRY_SP_2_0_GHZ_GROWLER_8_GB      =(SENTRY_FAMILY<<16)|0x0200,
                SENTRY_SP_2_0_GHZ_PHANTOM_0_GB      =(SENTRY_FAMILY<<16)|0x0300,
                SENTRY_SP_2_0_GHZ_PHANTOM_12_GB     =(SENTRY_FAMILY<<16)|0x0400,
                SENTRY_SP_1_86_GHZ_GROWLER_0_GB     =(SENTRY_FAMILY<<16)|0x0500,
                SENTRY_SP_1_86_GHZ_GROWLER_4_GB     =(SENTRY_FAMILY<<16)|0x0600,
                SENTRY_SP_2_13_GHZ_GROWLER_NO_BBU   =(SENTRY_FAMILY<<16)|0x0700,
                SENTRY_SP_2_13_GHZ_GROWLER_FULL_BBU =(SENTRY_FAMILY<<16)|0x0800,
                SENTRY_SP_2_0_GHZ_GROWLER_NO_BBU    =(SENTRY_FAMILY<<16)|0x0900,
                SENTRY_SP_1_60_GHZ_DC_NO_BBU        =(SENTRY_FAMILY<<16)|0x0A00,
                SENTRY_SP_2_0_GHZ_DC_SPARE_NO_BBU   =(SENTRY_FAMILY<<16)|0x0B00,

                // these values are from the resume prom spec, do not change

                EVERGREEN_SP_JASPER_CPU             =(EVERGREEN_FAMILY<<16)|0x0100,
                EHORNET_1GB_WO_BBU                  =(EVERGREEN_FAMILY<<16)|0X0200,
                EHORNET_1GB_W_2CELL_BBU             =(EVERGREEN_FAMILY<<16)|0X0300,
                EHORNET_1GB_W_3CELL_BBU             =(EVERGREEN_FAMILY<<16)|0X0400,
                EHORNET_2GB_WO_BBU                  =(EVERGREEN_FAMILY<<16)|0X0500,
                EHORNET_2GB_W_2CELL_BBU             =(EVERGREEN_FAMILY<<16)|0X0600,
                EHORNET_2GB_W_3CELL_BBU             =(EVERGREEN_FAMILY<<16)|0X0700,
                EPOSEIDON                           =(EVERGREEN_FAMILY<<16)|0X0800,
                ECOROMANDEL                         =(EVERGREEN_FAMILY<<16)|0X0900,
                ESUPERCELL                          =(EVERGREEN_FAMILY<<16)|0X0A00,
                EGLACIER                            =(EVERGREEN_FAMILY<<16)|0X0B00,
                ECOLDFRONT                          =(EVERGREEN_FAMILY<<16)|0X0C00,
                EERUPTION                           =(EVERGREEN_FAMILY<<16)|0X0D00,
                EERUPTION_10GB_W_BCM84833           =(EVERGREEN_FAMILY<<16)|0X0E00,
                EVERGREEN_SP_QUAD_JASPER_CPU        =(EVERGREEN_FAMILY<<16)|0x0F00,
                EERUPTION_REV_B                     =(EVERGREEN_FAMILY<<16)|0X1000,
                EVORTEX                             =(EVERGREEN_FAMILY<<16)|0X1100,
                EMOONLITE                           =(EVERGREEN_FAMILY<<16)|0X1200,
                EVORTEX_X8                          =(EVERGREEN_FAMILY<<16)|0X1300,
                ELANDSLIDE                          =(EVERGREEN_FAMILY<<16)|0X1400,
                EGLACIER_4S                         =(EVERGREEN_FAMILY<<16)|0X1500,
                EGLACIER_1S3M                       =(EVERGREEN_FAMILY<<16)|0X1600,

                INTREPID_SP_CPU_2_0_GHZ_NEH         =(INTREPID_FAMILY<<16)|0x0100,
                HAVOK                               =(INTREPID_FAMILY<<16)|0x0200,
                AVENGER_D                           =(INTREPID_FAMILY<<16)|0x0300,
                AVENGER_F                           =(INTREPID_FAMILY<<16)|0x0400,
                DEFENDER                            =(INTREPID_FAMILY<<16)|0x0500,
                SUPERNOVA                           =(INTREPID_FAMILY<<16)|0x0600,
                INTREPID_SP_CPU_2_53_GHZ_NEH        =(INTREPID_FAMILY<<16)|0x0700,
                INTREPID_SP_CPU_2_80_GHZ_NEH        =(INTREPID_FAMILY<<16)|0x0800,
                INTREPID_SP_CPU_3_20_GHZ_WSM        =(INTREPID_FAMILY<<16)|0x0900,
                INTREPID_SP_REV_B_CPU_2_40_GHZ_WSM  =(INTREPID_FAMILY<<16)|0x0A00,
                INTREPID_SP_REV_B_CPU_2_80_GHZ_WSM  =(INTREPID_FAMILY<<16)|0x0B00,

                // these values are from the resume prom spec, do not change

                STARSCREAM_SP_REV_A                 =(STARSCREAM_FAMILY<<16)|0x0100,
                STARSCREAM_SP_REV_B                 =(STARSCREAM_FAMILY<<16)|0x0200,
                //INTENTIONALLY_BLANK               =(STARSCREAM_FAMILY<<16)|0x0300,
                STARSCREAM_SP_REV_C_SSD             =(STARSCREAM_FAMILY<<16)|0x0400,
                STARSCREAM_SP_REV_C_MSATA           =(STARSCREAM_FAMILY<<16)|0x0500,

                MEGATRON_SP_REV_A                   =(MEGATRON_FAMILY<<16)|0x0100,
                MEGATRON_SP_REV_B                   =(MEGATRON_FAMILY<<16)|0x0200,
                MEGATRON_SP_E5_2660                 =(MEGATRON_FAMILY<<16)|0x0300,
                MEGATRON_SP_E5_2680                 =(MEGATRON_FAMILY<<16)|0x0400,
                MEGATRON_SP_E5_2660_REV_C           =(MEGATRON_FAMILY<<16)|0x0500,
                MEGATRON_SP_E5_2680_REV_C           =(MEGATRON_FAMILY<<16)|0x0600,
                MEGATRON_LITE_SP_REV_C              =(MEGATRON_FAMILY<<16)|0x0700,
                MEGATRON_SP_E5_2660_REV_C_GEN_3     =(MEGATRON_FAMILY<<16)|0x0800,
                MEGATRON_SP_E5_2680_REV_C_GEN_3     =(MEGATRON_FAMILY<<16)|0x0900,
                MEGATRON_LITE_SP_REV_C_GEN_3        =(MEGATRON_FAMILY<<16)|0x0A00,
                MEGATRON_HEAVY_SP_REV_C_GEN_3       =(MEGATRON_FAMILY<<16)|0x0B00,
                MEGATRON_SP_E5_2697V2_REV_C_GEN_3   =(MEGATRON_FAMILY<<16)|0x0C00,
                MEGATRON_SP_E5_2690V2_REV_C_GEN_3   =(MEGATRON_FAMILY<<16)|0x0D00,
                MEGATRON_SP_E5_2650V2_REV_C_GEN_3   =(MEGATRON_FAMILY<<16)|0x0E00,
                MEGATRON_SP_E5_2620V2_REV_C_GEN_3   =(MEGATRON_FAMILY<<16)|0x0F00,
                MEGATRON_SP_E5_2680V2_REV_C_GEN_3   =(MEGATRON_FAMILY<<16)|0x1000,

                DEVASTATOR_SP_REV_A                 =(DEVASTATOR_FAMILY<<16)|0x0100,
                HIGHTOWER_MEM_RISER_REV_A           =(DEVASTATOR_FAMILY<<16)|0x0200,
                DEVASTATOR_SP_REV_B                 =(DEVASTATOR_FAMILY<<16)|0x0300,
                HIGHTOWER_MEM_RISER_REV_B           =(DEVASTATOR_FAMILY<<16)|0x0400,
                DEVASTATOR_SP_REV_C                 =(DEVASTATOR_FAMILY<<16)|0x0500,
                HIGHTOWER_MEM_RISER_REV_C           =(DEVASTATOR_FAMILY<<16)|0x0600,

                // these values are from the resume prom spec, do not change

                BEACHCOMBER_PCB                     =(BEACHCOMBER_FAMILY<<16)|0x0100,
                BEACHCOMBER_PCB_REV_B               =(BEACHCOMBER_FAMILY<<16)|0x0200,
                BEACHCOMBER_PCB_REV_B_CPU_6_CORE    =(BEACHCOMBER_FAMILY<<16)|0x0300,
                BEACHCOMBER_PCB_REV_B_BCM57840_16GB =(BEACHCOMBER_FAMILY<<16)|0x0400,
                BEACHCOMBER_PCB_REV_B_BCM57840_24GB =(BEACHCOMBER_FAMILY<<16)|0x0500,
                BEACHCOMBER_PCB_REV_C_4C            =(BEACHCOMBER_FAMILY<<16)|0x0600,
                BEACHCOMBER_PCB_REV_C_6C            =(BEACHCOMBER_FAMILY<<16)|0x0700,
                BEACHCOMBER_PCB_REV_D_4C            =(BEACHCOMBER_FAMILY<<16)|0x0800,
                BEACHCOMBER_PCB_REV_D_6C            =(BEACHCOMBER_FAMILY<<16)|0x0900,
                BEACHCOMBER_PCB_FC_2C               =(BEACHCOMBER_FAMILY<<16)|0x0A00,
                // PCB for Beachcomber SIMULATOR
                BEACHCOMBER_PCB_SIM                 =(BEACHCOMBER_FAMILY<<16)|0xFF00,

                // Used by vVNX product; hypervisor specific
                MERIDIAN_SP_ESX                     =(MERIDIAN_FAMILY<<16)|0x0100,
                MERIDIAN_SP_KVM                     =(MERIDIAN_FAMILY<<16)|0x0200,
                MERIDIAN_SP_XEN                     =(MERIDIAN_FAMILY<<16)|0x0300,
                MERIDIAN_SP_HYPERV                  =(MERIDIAN_FAMILY<<16)|0x0400,
                // Used by vVNX product
                TUNGSTEN_SP                         =(MERIDIAN_FAMILY<<16)|0x0500,

                JETFIRE_SP_SANDYBRIDGE              =(JETFIRE_FAMILY<<16)|0x0100,
                JETFIRE_SP_E5_2660                  =(JETFIRE_FAMILY<<16)|0x0200,
                JETFIRE_SP_E5_2620                  =(JETFIRE_FAMILY<<16)|0x0300,
                JETFIRE_SP_E5_2609                  =(JETFIRE_FAMILY<<16)|0x0400,
                JETFIRE_SP_E5_2603                  =(JETFIRE_FAMILY<<16)|0x0500,
                JETFIRE_SP_E5_2603_1_20_GHZ         =(JETFIRE_FAMILY<<16)|0x0600,
                IRONHIDE_6G_SAS                     =(JETFIRE_FAMILY<<16)|0x0800,
                IRONHIDE_6G_SAS_REV_B               =(JETFIRE_FAMILY<<16)|0x0900,
                IRONHIDE_6G_SAS_REV_C               =(JETFIRE_FAMILY<<16)|0x0A00,
                JETFIRE_SP_E5_2660_REV_D            =(JETFIRE_FAMILY<<16)|0x0B00,
                JETFIRE_SP_E5_2620_REV_D            =(JETFIRE_FAMILY<<16)|0x0C00,
                JETFIRE_SP_E5_2609_REV_D            =(JETFIRE_FAMILY<<16)|0x0D00,
                JETFIRE_SP_E5_2603_REV_D            =(JETFIRE_FAMILY<<16)|0x0E00,
                JETFIRE_SP_E5_2603_1_20_GHZ_REV_D   =(JETFIRE_FAMILY<<16)|0x0F00,
                JETFIRE_SP_E5_2603_SPARE_REV_D      =(JETFIRE_FAMILY<<16)|0x1000,
                JETFIRE_SP_E5_2660_REV_B_GEN_3      =(JETFIRE_FAMILY<<16)|0x1100,
                JETFIRE_SP_E5_2620_REV_B_GEN_3      =(JETFIRE_FAMILY<<16)|0x1200,
                JETFIRE_SP_E5_2609_REV_B_GEN_3      =(JETFIRE_FAMILY<<16)|0x1300,
                JETFIRE_SP_E5_2603_REV_B_GEN_3      =(JETFIRE_FAMILY<<16)|0x1400,
                JETFIRE_SP_E5_2603_1_20_GHZ_REV_B_G3=(JETFIRE_FAMILY<<16)|0x1500,
                JETFIRE_SP_E5_2603_SPARE_REV_B_GEN_3=(JETFIRE_FAMILY<<16)|0x1600,
                JETFIRE_SP_E5_2620V2_REV_D_64GB     =(JETFIRE_FAMILY<<16)|0x1700,
                JETFIRE_SP_E5_2650V2_REV_D          =(JETFIRE_FAMILY<<16)|0x1800,
                JETFIRE_SP_E5_2630V2_REV_D          =(JETFIRE_FAMILY<<16)|0x1900,
                JETFIRE_SP_E5_2620V2_REV_D          =(JETFIRE_FAMILY<<16)|0x1A00,
                JETFIRE_SP_E5_2680V2_REV_D          =(JETFIRE_FAMILY<<16)|0x1B00,
                JETFIRE_SP_E5_2609V2_REV_D          =(JETFIRE_FAMILY<<16)|0x1C00,
                JETFIRE_SP_E5_2603V2_REV_D          =(JETFIRE_FAMILY<<16)|0x1D00,
                IRONHIDE_6G_SAS_REV_D               =(JETFIRE_FAMILY<<16)|0x1E00,

                // these values are from the resume prom spec, do not change

                SKYDIVE_SP_24_PORT_SXP              =(SKYDIVE_FAMILY<<16)|0x0100,
                SKYDIVE_SP_36_PORT_SXP              =(SKYDIVE_FAMILY<<16)|0x0200,
                SKYDIVE_SP_E5_2603                  =(SKYDIVE_FAMILY<<16)|0x0300,
                SKYDIVE_SP_E5_2620                  =(SKYDIVE_FAMILY<<16)|0x0400,
                SKYDIVE_SP_E5_2660                  =(SKYDIVE_FAMILY<<16)|0x0500,
                SKYDIVE_SP_E5_2620_RISER_0_ONLY     =(SKYDIVE_FAMILY<<16)|0x0600,

                CONTROL_STATION_MGMT                =(MGMT_MODULE_FAMILY<<16)|0x0100,
                AKULA_II_SAN_MGMT                   =(MGMT_MODULE_FAMILY<<16)|0x0200,

                SILVERBOLT_SP_25W                   =(SILVERBOLT_FAMILY<<16)|0x0100,
                SILVERBOLT_SP_40W                   =(SILVERBOLT_FAMILY<<16)|0x0200,

                STARFIRE_LCC_PLX0                   =(STARDUST_FAMILY<<16)|0x1000,
                STARFIRE_LCC_PLX1                   =(STARDUST_FAMILY<<16)|0x1100,
                STARFIRE_LCC_PLX2                   =(STARDUST_FAMILY<<16)|0x1200,
                STARFIRE_LCC_PLX3                   =(STARDUST_FAMILY<<16)|0x1300,

                TRITON_ERB_SP_REV_A                 =(TRITON_FAMILY<<16)|0x0100,
                TRITON_SP_REV_B                     =(TRITON_FAMILY<<16)|0x0200,
                TRITON_SP_SATA_SSD                  =(TRITON_FAMILY<<16)|0x0300,
                TRITON_SP_PCIE_SATA_SSD             =(TRITON_FAMILY<<16)|0x0400,
                LONGHAUL                            =(TRITON_FAMILY<<16)|0x0500,

                DEIMOS_SP_EX_GENERIC                =(DEIMOS_FAMILY<<16)|0x0100,
                DEIMOS_MEMORY_RISER_REV_A           =(DEIMOS_FAMILY<<16)|0x0200,
                DEIMOS_IO_BOARD_REV_A               =(DEIMOS_FAMILY<<16)|0x0300,
                DEIMOS_SP_P_0_5                     =(DEIMOS_FAMILY<<16)|0x0400,
                DEIMOS_MEMORY_RISER_P_0_5           =(DEIMOS_FAMILY<<16)|0x0500,
                DEIMOS_SP_P_1                       =(DEIMOS_FAMILY<<16)|0x0600,
                DEIMOS_MEMORY_RISER_P_1             =(DEIMOS_FAMILY<<16)|0x0700,
                DEIMOS_IO_BOARD_REV_B_P_1           =(DEIMOS_FAMILY<<16)|0x0800,
                DEIMOS_SP_E7_4880_REV_D             =(DEIMOS_FAMILY<<16)|0x0900,
                DEIMOS_MEMORY_RISER_REV_C           =(DEIMOS_FAMILY<<16)|0x0A00,
                DEIMOS_IO_BOARD_REV_C               =(DEIMOS_FAMILY<<16)|0x0B00,

                // these values are from the resume prom spec, do not change

                EUROPA_SAS_DIB                      =(EUROPA_FAMILY<<16)|0x0100,
                EUROPA_SP_TIER_4                    =(EUROPA_FAMILY<<16)|0x0200,
                EUROPA_SP_TIER_3                    =(EUROPA_FAMILY<<16)|0x0300,
                EUROPA_SP_TIER_2                    =(EUROPA_FAMILY<<16)|0x0400,
                EUROPA_SAS_DIB_REV_B                =(EUROPA_FAMILY<<16)|0x0500,
                EUROPA_SP_TIER_4_REV_B              =(EUROPA_FAMILY<<16)|0x0600,
                EUROPA_SP_TIER_3_REV_B              =(EUROPA_FAMILY<<16)|0x0700,
                EUROPA_SP_TIER_2_REV_B              =(EUROPA_FAMILY<<16)|0x0800,
                EUROPA_SP_TIER_1_REV_B              =(EUROPA_FAMILY<<16)|0x0900,
                EUROPA_SP_TIER_4_135W_REV_B         =(EUROPA_FAMILY<<16)|0x0A00,
                EUROPA_ROC_DIB                      =(EUROPA_FAMILY<<16)|0x0B00,
                EUROPA_SP_TIER_A_B_REV_B            =(EUROPA_FAMILY<<16)|0x0C00,
                EUROPA_SP_TIER_C_REV_B              =(EUROPA_FAMILY<<16)|0x0D00,
                EUROPA_SP_TIER_D_REV_B              =(EUROPA_FAMILY<<16)|0x0E00,
                EUROPA_SP_TIER_A_REV_B              =(EUROPA_FAMILY<<16)|0x0F00,
                EUROPA_SP_TIER_B_REV_B              =(EUROPA_FAMILY<<16)|0x1000,
                EUROPA_SAS_DIB_1U                   =(EUROPA_FAMILY<<16)|0x1100,

                GORGON_X                            =(SLIC_2_0_FAMILY<<16)|0x0100,
                RAINFALL_X                          =(SLIC_2_0_FAMILY<<16)|0x0200,
                DUSTDEVIL_X                         =(SLIC_2_0_FAMILY<<16)|0x0300,
                SNOWDEVIL_X                         =(SLIC_2_0_FAMILY<<16)|0x0400,
                ROCKSLIDE_X                         =(SLIC_2_0_FAMILY<<16)|0x0500,
                VORTEXQ_X                           =(SLIC_2_0_FAMILY<<16)|0x0600,
                THUNDERHEAD_X                       =(SLIC_2_0_FAMILY<<16)|0x0700,
                STARFALL_X                          =(SLIC_2_0_FAMILY<<16)|0x0800,
                DOWNBURST_X                         =(SLIC_2_0_FAMILY<<16)|0x0900,
                MAELSTROM_X                         =(SLIC_2_0_FAMILY<<16)|0x0A00,
                BLAZAR_X                            =(SLIC_2_0_FAMILY<<16)|0x0B00,
                DOWNBURST_X_RDMA                    =(SLIC_2_0_FAMILY<<16)|0x0C00,
                // When adding new IO Modules, also increment MAX_SLIC_2_0_COUNT
                // and add the new module to SPID (SpidInitSupportedIoModules).

                HYPERION_SP_REV_A                   =(HYPERION_FAMILY<<16)|0x0100,
                HYPERION_SP_12C_REV_A               =(HYPERION_FAMILY<<16)|0x0200,
                HYPERION_SP_6C_85W_REV_A            =(HYPERION_FAMILY<<16)|0x0300,
                HYPERION_SP_8C_85W_REV_A            =(HYPERION_FAMILY<<16)|0x0400,
                HYPERION_SP_8C_135W_REV_A           =(HYPERION_FAMILY<<16)|0x0500,
                HYPERION_SP_10C_105W_REV_A          =(HYPERION_FAMILY<<16)|0x0600,
                HYPERION_SP_12C_105W_REV_A          =(HYPERION_FAMILY<<16)|0x0700,
                HYPERION_SP_12C_120W_REV_A          =(HYPERION_FAMILY<<16)|0x0800,
                HYPERION_SP_14C_145W_REV_A          =(HYPERION_FAMILY<<16)|0x0900,
                LAPETUS_12G_SAS_REV_A               =(HYPERION_FAMILY<<16)|0x0A00,
                LAPETUS_12G_SAS_REV_B               =(HYPERION_FAMILY<<16)|0x0B00,
                WAXING_DEBUG_MP                     =(HYPERION_FAMILY<<16)|0x0C00,
                HYPERION_SP_E5_2680V3_REV_B         =(HYPERION_FAMILY<<16)|0x0E00,
                HYPERION_SP_E5_2640V3_REV_B         =(HYPERION_FAMILY<<16)|0x0F00,
                HYPERION_SP_E5_2620V3_REV_B         =(HYPERION_FAMILY<<16)|0x1000,

                // these values are from the resume prom spec, do not change

                OBERON_SP_85W_REV_A                 =(OBERON_FAMILY<<16)|0x0100,
                OBERON_SP_105W_REV_A                =(OBERON_FAMILY<<16)|0x0200,
                OBERON_SP_120W_REV_A                =(OBERON_FAMILY<<16)|0x0300,
                OBERON_SXP                          =(OBERON_FAMILY<<16)|0x0400,
                OBERON_SP_E5_2603V3_REV_B           =(OBERON_FAMILY<<16)|0x0500,
                OBERON_SP_E5_2630V3_REV_B           =(OBERON_FAMILY<<16)|0x0600,
                OBERON_SP_E5_2609V3_REV_B           =(OBERON_FAMILY<<16)|0x0700,
                OBERON_SP_E5_2660V3_REV_B           =(OBERON_FAMILY<<16)|0x0800,

                COLOSSUS_INTERPOSER                 =(COLOSSUS_FAMILY<<16)|0x0001,
                COLOSSUS_INTERPOSER_V2              =(COLOSSUS_FAMILY<<16)|0x0002,
                COLOSSUS_INTERPOSER_V3              =(COLOSSUS_FAMILY<<16)|0x0003,

                FLICKERTAIL_4GB                     =(PCIE_IO_MODULE_FAMILY<<16)|0x000C,
                FLICKERTAIL_8GB                     =(PCIE_IO_MODULE_FAMILY<<16)|0x000D,
                FLICKERTAIL_16GB                    =(PCIE_IO_MODULE_FAMILY<<16)|0x000E,
                FLICKERTAIL_32GB                    =(PCIE_IO_MODULE_FAMILY<<16)|0x000F,

                LUNA_SP_REV_A                       =(LUNA_FAMILY<<16)|0x0100,
                LUNA_SP_REV_A_12C                   =(LUNA_FAMILY<<16)|0x0200,
                LUNA_SP_CDVT_14C_BDW                =(LUNA_FAMILY<<16)|0x0300,
                LUNA_SP_CDVT_16C_BDW                =(LUNA_FAMILY<<16)|0x0400,
                LUNA_SP_CDVT_18C_BDW                =(LUNA_FAMILY<<16)|0x0500,
                LUNA_SP_CDVT_20C_BDW                =(LUNA_FAMILY<<16)|0x0600,
                LUNA_SP_CDVT_22C_BDW                =(LUNA_FAMILY<<16)|0x0700,
                LUNA_SP_CDVT_12C_BDW                =(LUNA_FAMILY<<16)|0x0800,

                WARTHOG                             =(INFINITY_FAMILY<<16)|0x0100,
                MONGOOSE                            =(INFINITY_FAMILY<<16)|0x0200,
                MAMMOTH                             =(INFINITY_FAMILY<<16)|0x0300,
                PROWLER_BASEBOARD                   =(INFINITY_FAMILY<<16)|0x0400,
                PHANTOM_BASEBOARD                   =(INFINITY_FAMILY<<16)|0x0500,
                PELICAN                             =(INFINITY_FAMILY<<16)|0x0600,
                BANSHEE                             =(INFINITY_FAMILY<<16)|0x0700,

                BENNU_LOW_PROFILE_NVRAM_CARD        =(DATA_DOMAIN_FAMILY<<16)|0x0000,
                PHOENIX_FULL_HEIGHT_NVRAM_CARD      =(DATA_DOMAIN_FAMILY<<16)|0x0100,

                CHASSIS_MANAGEMENT_CONTROLLER       =(ISILON_FAMILY<<16)|0x0100,
                ISD_LOX_SSD                         =(ISILON_FAMILY<<16)|0x0800,
                ISD_LOX_NVRAM_512MB                 =(ISILON_FAMILY<<16)|0x0900,
                ISD_LOX_NVRAM_1GB                   =(ISILON_FAMILY<<16)|0x0A00,
                ISD_LOX_NVRAM_2GB                   =(ISILON_FAMILY<<16)|0x0B00,
                ISD_LOX_NVRAM_4GB                   =(ISILON_FAMILY<<16)|0x0C00,
                ISD_LOX_NVRAM_8GB                   =(ISILON_FAMILY<<16)|0x0D00,
                ERMINE_SEFC                         =(ISILON_FAMILY<<16)|0x0E00,

                TIGON_MATRIX_ENC                    =(TIGON_FAMILY<<16)|0x3031,
                TIGON_MATRIX_ENC_REV_C              =(TIGON_FAMILY<<16)|0x3032,

                // these values are from the resume prom spec, do not change

                UNRECOGNIZED_MOD                    =(NO_FAMILY<<16)|0x0100
} HW_MODULE_TYPE, *PHW_MODULE_TYPE;

/* Total number of IO modules plus 
 * - DEBUG_FAMILY [ie: Seacat, etc...]
 * - DAUGHTER_CARD_FAMILY [ie: Growler, etc...]
 * - BEM (Part of Jetfire) [ie: Ironhide, etc...]
 * - ESLIC (Part of Evergreen) [ie: eGlacier, etc...]
 */

#define MAX_DEBUG_FAMILY_COUNT          5
#define MAX_DAUGHTER_CARD_FAMILY_COUNT  10
#define MAX_BEM_COUNT                   6
#define MAX_SLIC_COUNT                  102
#define MAX_SLIC_2_0_COUNT              12
#define MAX_ESLIC_COUNT                 14
#define MAX_IOMODULE_COUNT             (MAX_DEBUG_FAMILY_COUNT +            \
                                        MAX_DAUGHTER_CARD_FAMILY_COUNT +    \
                                        MAX_BEM_COUNT +                     \
                                        MAX_SLIC_COUNT +                    \
                                        MAX_SLIC_2_0_COUNT +                \
                                        MAX_ESLIC_COUNT)

#endif  // _FAMILY_FRU_ID_H_
