/*
 * place copyright statement here -- 2000
 */

/******************************************************/
/* G EN E R A T E D   F I L E -- D o  n o t  E D I T  */
/* alter trc_tree.txt and/or trc_text.txt and regen   */
/******************************************************/

/*
 * generated by tree2envh.c compiled on Mar 30 2000
 * from files /TBS/ /TBS/
 */

#if !defined(FLARE_TRC_TRC_H)
#define FLARE_TRC_TRC_H
#if TRC_DEVELOP
#if !defined(TRC_TRC_FLAG)
    #define TRC_TRC_FLAG (TRC_ALL)
#endif
#if !defined(TRC_TRC_ACTIVE)
     #define TRC_TRC_ACTIVE (TRC_entry)
#endif
#else
#if !defined(TRC_TRC_FLAG)
    #define TRC_TRC_FLAG (TRC_ALL)
#endif
#if !defined(TRC_TRC_ACTIVE)
     #define TRC_TRC_ACTIVE (0)
#endif
#endif /* TRC_DEVELOP */

TRC_fgen (TRC_TRC_flag, (TRC_flag_T)TRC_TRC_ACTIVE);

#endif /* !defined(FLARE_TRC_TRC_H) */ /* last line infile */
