/*
 * place copyright statement here -- 2000
 */

/******************************************************/
/* G EN E R A T E D   F I L E -- D o  n o t  E D I T  */
/* alter trc_tree.txt and/or trc_text.txt and regen   */
/******************************************************/

/*
 * generated by tree2envh.c compiled on Mar 30 2000
 * from files /TBS/ /TBS/
 */

#if !defined(GETSPIDS_TRC_H)
#define GETSPIDS_TRC_H
#if TRC_DEVELOP
#if !defined(TRC_GETSPIDS_FLAG)
    #define TRC_GETSPIDS_FLAG (0xFFFFffff)
#endif
#if !defined(TRC_GETSPIDS_ACTIVE)
     #define TRC_GETSPIDS_ACTIVE (000)
#endif
#else
#if !defined(TRC_GETSPIDS_FLAG)
    #define TRC_GETSPIDS_FLAG (0xFFFFffff)
#endif
#if !defined(TRC_GETSPIDS_ACTIVE)
     #define TRC_GETSPIDS_ACTIVE (000)
#endif
#endif /* TRC_DEVELOP */

TRC_fgen (TRC_GETSPIDS_flag, (TRC_flag_T)TRC_GETSPIDS_ACTIVE);

#endif /* !defined(GETSPIDS_TRC_H) */ /* last line infile */
