// DO NOT EDIT THIS FILE!
// Instead, edit the Perl module ICA::IRFS::Structures

// Generated by: mferson
// Generated at: Thu Sep 20 15:01:44 2007
// Generated on: ESD-FERSON

#ifndef	ICA_IRFS_STRUCTURES_H
#define	ICA_IRFS_STRUCTURES_H

// Automatically generated #defines,
// based on exported subroutine names

#define	IRFS_IR_VOLUME_IDENTIFIER	"$ICA_IMAGE_REPOSITORY_FILESYSTEM$"
#define	IRFS_BD_VOLUME_IDENTIFIER	"$EMC_BOOT_DIRECTIVE_FS$"

// pack these structures on 1-byte boundaries,
// which is standard for wire protocols

#pragma pack(1)

// ELEMENT_DESCRIPTOR
typedef struct
{
	BOOL_8E	InUse;
	UINT_32E	ElementNumber;
	CHAR_8E	ElementName[128];
	CHAR_8E	ElementChecksum[128];
	UINT_64E	DataLength;
	UINT_32E	StartingChunk;
	UINT_32E	ChunkCount;
	BOOL_8E	WriteInProgress;
	UINT_32E	NextElementInChain;
	UINT_32E	PrevElementInChain;
	BYTE_8E	Padding[226];
} ELEMENT_DESCRIPTOR;


// VOLUME_HEADER
typedef struct
{
	CHAR_8E	VolumeIdentifier[128];
	CHAR_8E	VolumeName[128];
	UINT_64E	VolumeSize;
	UINT_32E	VolumeTimestamp;
	UINT_32E	VolumeMagical;
	UINT_32E	FeatureRevision;
	UINT_32E	ElementDescriptorCount;
	UINT_32E	ChunkSize;
	UINT_32E	ChunkCount;
	BITMAP_32E	DescriptorMap[4];
	BITMAP_32E	ChunkMap[32];
	BYTE_8E	WWNSeed[8];
	BOOL_8E	RebuildInProgress;
	BYTE_8E	Padding[71];
} VOLUME_HEADER;



// Return to default packing behavior
#pragma pack()

#endif // ICA_IRFS_STRUCTURES_H
