/*
 * place copyright statement here -- 2000 - 2009
 */

/******************************************************/
/* G E N E R A T E D   F I L E -- D o  n o t  E D I T */
/* alter trc_tree.txt and/or trc_text.txt and regen   */
/******************************************************/
// NOTE*** the generator is currently broken ***

/*
 * generated by tree2envh.c compiled on Apr 19 2000
 * from files /TBS/ /TBS/
 */

#if !defined(TRC_ENVIRON1_H)
#define      TRC_ENVIRON1_H

/*
 * make sure TRC_COMP is not defined, it must be defined
 * by one of the following statement groups.
 */
#undef TRC_COMP
/*
 * addslave components
 */

#if defined (TRC_COMP_ADDSLAVE) \
|| (defined(TRC_GROUP_ADDSLAVE) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "ADDSLAVE"
#define TRC_COMP ADDSLAVE
#include "addslave_trc.h"
#endif

/*
 * admdisp components
 */

#if defined (TRC_COMP_ADMDISP) \
|| (defined(TRC_GROUP_ADMDISP) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "ADMDISP"
#define TRC_COMP ADMDISP
#include "admdisp_trc.h"
#endif

/*
 * admeng components
 */

#if defined (TRC_COMP_ADMENG) \
|| (defined(TRC_GROUP_ADMENG) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "ADMENG"
#define TRC_COMP ADMENG
#include "admeng_trc.h"
#endif

/*
 * 1shot components
 */

#if defined (TRC_COMP_1SHOT) \
|| (defined(TRC_GROUP_1SHOT) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "1SHOT"
#define TRC_COMP 1SHOT
#include "1shot_trc.h"
#endif

/*
 * bindobj components
 */

#if defined (TRC_COMP_BINDOBJ) \
|| (defined(TRC_GROUP_BINDOBJ) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "BINDOBJ"
#define TRC_COMP BINDOBJ
#include "bindobj_trc.h"
#endif

/*
 * blow components
 */

#if defined (TRC_COMP_BLOW) \
|| (defined(TRC_GROUP_BLOW) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "BLOW"
#define TRC_COMP BLOW
#include "blow_trc.h"
#endif

/*
 * cds components
 */

#if defined (TRC_COMP_CDS) \
|| (defined(TRC_GROUP_CDS) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "CDS"
#define TRC_COMP CDS
#include "cds_trc.h"
#endif

/*
 * chgslave components
 */

#if defined (TRC_COMP_CHGSLAVE) \
|| (defined(TRC_GROUP_CHGSLAVE) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "CHGSLAVE"
#define TRC_COMP CHGSLAVE
#include "chgslave_trc.h"
#endif

/*
 * chkimg components
 */

#if defined (TRC_COMP_CHKIMG) \
|| (defined(TRC_GROUP_CHKIMG) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "CHKIMG"
#define TRC_COMP CHKIMG
#include "chkimg_trc.h"
#endif

/*
 * config components
 */

#if defined (TRC_COMP_CONFIG) \
|| (defined(TRC_GROUP_CONFIG) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "CONFIG"
#define TRC_COMP CONFIG
#include "config_trc.h"
#endif

/*
 * FEDisk component
 */

#if defined (TRC_COMP_FEDISK) \
|| (defined(TRC_GROUP_FEDISK) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "FEDISK"
#define TRC_COMP FEDISK
#include "fedisk_trc.h"
#endif

/*
 * cpm components
 */

#if defined (TRC_COMP_CPMCOPY) \
|| (defined(TRC_GROUP_CPM) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "CPM"
#define TRC_COMP CPMCOPY
#include "cpm_copy_trc.h"
#endif

#if defined (TRC_COMP_CPMCTRL) \
|| (defined(TRC_GROUP_CPM) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "CPM"
#define TRC_COMP CPMCTRL
#include "cpm_ctrl_trc.h"
#endif

#if defined (TRC_COMP_CPMDRVR) \
|| (defined(TRC_GROUP_CPM) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "CPM"
#define TRC_COMP CPMDRVR
#include "cpm_drvr_trc.h"
#endif

#if defined (TRC_COMP_CPMGSKT) \
|| (defined(TRC_GROUP_CPM) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "CPM"
#define TRC_COMP CPMGSKT
#include "cpm_gskt_trc.h"
#endif

/* #if defined (TRC_COMP_CPMLIB) \
|| (defined(TRC_GROUP_CPM) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "CPM"
#define TRC_COMP CPMLIB
#include "cpm_lib_trc.h"
#endif */

#if defined (TRC_COMP_CPMMGMT) \
|| (defined(TRC_GROUP_CPM) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "CPM"
#define TRC_COMP CPMMGMT
#include "cpm_mgmt_trc.h"
#endif

#if defined (TRC_COMP_CPMPARSE) \
|| (defined(TRC_GROUP_CPM) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "CPM"
#define TRC_COMP CPMPARSE
#include "cpm_parse_trc.h"
#endif

#if defined (TRC_COMP_CPMPROC) \
|| (defined(TRC_GROUP_CPM) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "CPM"
#define TRC_COMP CPMPROC
#include "cpm_proc_trc.h"
#endif

/*
 * creatlnk components
 */

#if defined (TRC_COMP_CREATLNK) \
|| (defined(TRC_GROUP_CREATLNK) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "CREATLNK"
#define TRC_COMP CREATLNK
#include "creatlnk_trc.h"
#endif

/*
 * creatmir components
 */

#if defined (TRC_COMP_CREATMIR) \
|| (defined(TRC_GROUP_CREATMIR) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "CREATMIR"
#define TRC_COMP CREATMIR
#include "creatmir_trc.h"
#endif

/*
 * daq components
 */

#if defined (TRC_COMP_DAQ) \
|| (defined(TRC_GROUP_DAQ) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "DAQ"
#define TRC_COMP DAQ
#include "daq_trc.h"
#endif

/*
 * destmir components
 */

#if defined (TRC_COMP_DESTMIR) \
|| (defined(TRC_GROUP_DESTMIR) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "DESTMIR"
#define TRC_COMP DESTMIR
#include "destmir_trc.h"
#endif

/*
 * dgint components
 */

#if defined (TRC_COMP_DGINT) \
|| (defined(TRC_GROUP_DGINT) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "DGINT"
#define TRC_COMP DGINT
#include "dgint_trc.h"
#endif

/*
 * disktest components
 */

#if defined (TRC_COMP_DISKTEST) \
|| (defined(TRC_GROUP_DISKTEST) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "DISKTEST"
#define TRC_COMP DISKTEST
#include "disktest_trc.h"
#endif

/*
 * dls1lock components
 */

#if defined (TRC_COMP_DLS1LOCK) \
|| (defined(TRC_GROUP_DLS1LOCK) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "DLS1LOCK"
#define TRC_COMP DLS1LOCK
#include "dls1lock_trc.h"
#endif

/*
 * dlsdrvr components
 */

#if defined (TRC_COMP_DLSDRVR) \
|| (defined(TRC_GROUP_DLSDRVR) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "DLSDRVR"
#define TRC_COMP DLSDRVR
#include "dlsdrvr_trc.h"
#endif

/*
 * dlsexp components
 */

#if defined (TRC_COMP_DLSEXP) \
|| (defined(TRC_GROUP_DLSEXP) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "DLSEXP"
#define TRC_COMP DLSEXP
#include "dlsexp_trc.h"
#endif

/*
 * dls components
 */

#if defined (TRC_COMP_DLSEXT) \
|| (defined(TRC_GROUP_DLS) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "DLSEXT"
#define TRC_COMP DLSEXT
#include "dlsext_trc.h"
#endif

/*
 * dlsutil components
 */

#if defined (TRC_COMP_DLSUTIL) \
|| (defined(TRC_GROUP_DLSUTIL) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "DLSUTIL"
#define TRC_COMP DLSUTIL
#include "dlsutil_trc.h"
#endif

/*
 * dumpman components
 */

#if defined (TRC_COMP_DUMPMAN) \
|| (defined(TRC_GROUP_DUMPMAN) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "DUMPMAN"
#define TRC_COMP DUMPMAN
#include "dumpman_trc.h"
#endif

/*
 * endpt components
 */

#if defined (TRC_COMP_ENDPT) \
|| (defined(TRC_GROUP_ENDPT) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "ENDPT"
#define TRC_COMP ENDPT
#include "endpt_trc.h"
#endif

/*
 * enummir components
 */

#if defined (TRC_COMP_ENUMMIR) \
|| (defined(TRC_GROUP_ENUMMIR) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "ENUMMIR"
#define TRC_COMP ENUMMIR
#include "enummir_trc.h"
#endif

/*
 * enumobjs components
 */

#if defined (TRC_COMP_ENUMOBJS) \
|| (defined(TRC_GROUP_ENUMOBJS) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "ENUMOBJS"
#define TRC_COMP ENUMOBJS
#include "enumobjs_trc.h"
#endif

/*
 * foo components
 */

#if defined (TRC_COMP_EVIL) \
|| (defined(TRC_GROUP_FOO) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "EVIL"
#define TRC_COMP EVIL
#include "*NULL*"
#endif

/*
 * fakelc components
 */

#if defined (TRC_COMP_FAKELC) \
|| (defined(TRC_GROUP_FAKELC) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "FAKELC"
#define TRC_COMP FAKELC
#include "fakelc_trc.h"
#endif

/*
 * far components
 */

#if defined (TRC_COMP_FARD) \
|| (defined(TRC_GROUP_FARD) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_COMP FARD
#include "far_trc.h"
#endif

/*
 * fliptest components
 */

#if defined (TRC_COMP_FLIPTEST) \
|| (defined(TRC_GROUP_FLIPTEST) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "FLIPTEST"
#define TRC_COMP FLIPTEST
#include "fliptest_trc.h"
#endif

/*
 * fracsync components
 */

#if defined (TRC_COMP_FRACSYNC) \
|| (defined(TRC_GROUP_FRACSYNC) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "FRACSYNC"
#define TRC_COMP FRACSYNC
#include "fracsync_trc.h"
#endif

/*
 * getdrvr components
 */

#if defined (TRC_COMP_GETDRVR) \
|| (defined(TRC_GROUP_GETDRVR) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "GETDRVR"
#define TRC_COMP GETDRVR
#include "getdrvr_trc.h"
#endif

/*
 * getgen components
 */

#if defined (TRC_COMP_GETGEN) \
|| (defined(TRC_GROUP_GETGEN) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "GETGEN"
#define TRC_COMP GETGEN
#include "getgen_trc.h"
#endif

/*
 * getimg components
 */

#if defined (TRC_COMP_GETIMG) \
|| (defined(TRC_GROUP_GETIMG) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "GETIMG"
#define TRC_COMP GETIMG
#include "getimg_trc.h"
#endif

/*
 * getmir components
 */

#if defined (TRC_COMP_GETMIR) \
|| (defined(TRC_GROUP_GETMIR) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "GETMIR"
#define TRC_COMP GETMIR
#include "getmir_trc.h"
#endif

/*
 * getspids components
 */

#if defined (TRC_COMP_GETSPIDS) \
|| (defined(TRC_GROUP_GETSPIDS) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "GETSPIDS"
#define TRC_COMP GETSPIDS
#include "getspids_trc.h"
#endif

/*
 * hash components
 */

#if defined (TRC_COMP_HASH) \
|| (defined(TRC_GROUP_HASH) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_COMP HASH
#include "hash_trc.h"
#endif

/*
 * hosttools components
 */

#if defined (TRC_COMP_HOSTTOOLS) \
|| (defined(TRC_GROUP_HOSTTOOLS) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "HOSTTOOLS"
#define TRC_COMP HOSTTOOLS
#include "hosttools_trc.h"
#endif

/*
 * k10admin components
 */

#if defined (TRC_COMP_K10ADMIN) \
|| (defined(TRC_GROUP_K10ADMIN) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "K10ADMIN"
#define TRC_COMP K10ADMIN
#include "k10admin_trc.h"
#endif

/*
 * k10app components
 */

#if defined (TRC_COMP_K10APP) \
|| (defined(TRC_GROUP_K10APP) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "K10APP"
#define TRC_COMP K10APP
#include "k10app_trc.h"
#endif

/*
 * k10drvrs components
 */

#if defined (TRC_COMP_K10DRVRS) \
|| (defined(TRC_GROUP_K10DRVRS) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "K10DRVRS"
#define TRC_COMP K10DRVRS
#include "k10drvrs_trc.h"
#endif

/*
 * k10elib components
 */

#if defined (TRC_COMP_K10ELIB) \
|| (defined(TRC_GROUP_K10ELIB) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "K10ELIB"
#define TRC_COMP K10ELIB
#include "k10elib_trc.h"
#endif

/*
 * k10falib components
 */

#if defined (TRC_COMP_K10FALIB) \
|| (defined(TRC_GROUP_K10FALIB) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "K10FALIB"
#define TRC_COMP K10FALIB
#include "k10falib_trc.h"
#endif

/*
 * k10glob components
 */

#if defined (TRC_COMP_K10GLOB) \
|| (defined(TRC_GROUP_K10GLOB) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "K10GLOB"
#define TRC_COMP K10GLOB
#include "k10glob_trc.h"
#endif

/*
 * k10gov components
 */

#if defined (TRC_COMP_K10GOV) \
|| (defined(TRC_GROUP_K10GOV) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "K10GOV"
#define TRC_COMP K10GOV
#include "k10gov_trc.h"
#endif

/*
 * k10halib components
 */

#if defined (TRC_COMP_K10HALIB) \
|| (defined(TRC_GROUP_K10HALIB) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "K10HALIB"
#define TRC_COMP K10HALIB
#include "k10halib_trc.h"
#endif

/*
 * k10insdrvr components
 */

#if defined (TRC_COMP_K10INSDRVR) \
|| (defined(TRC_GROUP_K10INSDRVR) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "K10INSDRVR"
#define TRC_COMP K10INSDRVR
#include "k10insdrvr_trc.h"
#endif

/*
 * K10IoMarshal Components
 */

#if defined (TRC_COMP_K10IOMARSHAL) \
|| (defined(TRC_GROUP_K10IOMARSHAL) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_COMP K10IOMARSHAL
#include "K10IoMarshal_trc.h"
#endif


/*
 * k10kill components
 */

#if defined (TRC_COMP_K10KILL) \
|| (defined(TRC_GROUP_K10KILL) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "K10KILL"
#define TRC_COMP K10KILL
#include "k10kill_trc.h"
#endif

/*
 * k10krnlmsg components
 */

#if defined (TRC_COMP_K10KRNLMSG) \
|| (defined(TRC_GROUP_K10KRNLMSG) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "K10KRNLMSG"
#define TRC_COMP K10KRNLMSG
#include "k10krnlmsg_trc.h"
#endif

/*
 * k10miscutil components
 */

#if defined (TRC_COMP_K10MISCUTIL) \
|| (defined(TRC_GROUP_K10MISCUTIL) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "K10MISCUTIL"
#define TRC_COMP K10MISCUTIL
#include "k10miscutil_trc.h"
#endif

/*
 * k10palib components
 */

#if defined (TRC_COMP_K10PALIB) \
|| (defined(TRC_GROUP_K10PALIB) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "K10PALIB"
#define TRC_COMP K10PALIB
#include "k10palib_trc.h"
#endif

/*
 * k10setup components
 */

#if defined (TRC_COMP_K10SETUP) \
|| (defined(TRC_GROUP_K10SETUP) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "K10SETUP"
#define TRC_COMP K10SETUP
#include "k10setup_trc.h"
#endif

/*
 * k10syslib components
 */

#if defined (TRC_COMP_K10SYSLIB) \
|| (defined(TRC_GROUP_K10SYSLIB) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "K10SYSLIB"
#define TRC_COMP K10SYSLIB
#include "k10syslib_trc.h"
#endif

/*
 * kfiagent components
 */

#if defined (TRC_COMP_KFIAGENT) \
|| (defined(TRC_GROUP_KFIAGENT) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "KFIAGENT"
#define TRC_COMP KFIAGENT
#include "kfiagent_trc.h"
#endif

/*
 * kfid components
 */

#if defined (TRC_COMP_KFID) \
|| (defined(TRC_GROUP_KFID) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "KFID"
#define TRC_COMP KFID
#include "kfid_trc.h"
#endif

/*
 * kfidrvr components
 */

#if defined (TRC_COMP_KFIDRVR) \
|| (defined(TRC_GROUP_KFIDRVR) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "KFIDRVR"
#define TRC_COMP KFIDRVR
#include "kfidrvr_trc.h"
#endif

/*
 * kfiinsdrvr components
 */

#if defined (TRC_COMP_KFIINSDRVR) \
|| (defined(TRC_GROUP_KFIINSDRVR) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "KFIINSDRVR"
#define TRC_COMP KFIINSDRVR
#include "kfiinsdrvr_trc.h"
#endif

/*
 * kfimisc components
 */

#if defined (TRC_COMP_KFIMISC) \
|| (defined(TRC_GROUP_KFIMISC) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MFIMISC"
#define TRC_COMP KFIMISC
#include "kfimisc_trc.h"
#endif

/*
 * kfipipe components
 */

#if defined (TRC_COMP_KFIPIPE) \
|| (defined(TRC_GROUP_KFIPIPE) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "KFIPIPE"
#define TRC_COMP KFIPIPE
#include "kfipipe_trc.h"
#endif

/*
 * kfitest components
 */

#if defined (TRC_COMP_KFITEST) \
|| (defined(TRC_GROUP_KFITEST) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "KFITEST"
#define TRC_COMP KFITEST
#include "kfitest_trc.h"
#endif

/*
 * kfiucls components
 */

#if defined (TRC_COMP_KFIUCLS) \
|| (defined(TRC_GROUP_KFIUCLS) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "KFIUCLS"
#define TRC_COMP KFIUCLS
#include "kfiucls_trc.h"
#endif

/*
 * ktrace components
 */

#if defined (TRC_COMP_KTRACE) \
|| (defined(TRC_GROUP_KTRACE) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "KTRACE"
#define TRC_COMP KTRACE
#include "ktrace_trc.h"
#endif

/*
 * mem components
 */

#if defined (TRC_COMP_MEM) \
|| (defined(TRC_GROUP_MEM) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MEM"
#define TRC_COMP MEM
#include "mem_trc.h"
#endif

/*
 * mgmtcom components
 */

#if defined (TRC_COMP_MGMTCOM) \
|| (defined(TRC_GROUP_MGMTCOM) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MGMTCOM"
#define TRC_COMP MGMTCOM
#include "mgmtcom_trc.h"
#endif

/*
 * minptapi components
 */

#if defined (TRC_COMP_MINPTAPI) \
|| (defined(TRC_GROUP_MINPTAPI) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MINTAPI"
#define TRC_COMP MINPTAPI
#include "minptapi_trc.h"
#endif

/*
 * minptcom components
 */

#if defined (TRC_COMP_MINPTCOM) \
|| (defined(TRC_GROUP_MINPTCOM) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MINPTCOM"
#define TRC_COMP MINPTCOM
#include "minptcom_trc.h"
#endif

/*
 * minptfcb components
 */

#if defined (TRC_COMP_MINPTFCB) \
|| (defined(TRC_GROUP_MINPTFCB) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MINPTFCB"
#define TRC_COMP MINPTFCB
#include "minptfcb_trc.h"
#endif

/*
 * minptfcf components
 */

#if defined (TRC_COMP_MINPTFCF) \
|| (defined(TRC_GROUP_MINPTFCF) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MINPTFCF"
#define TRC_COMP MINPTFCF
#include "minptfcf_trc.h"
#endif

/*
 * minpthptl components
 */

#if defined (TRC_COMP_MINPTHPTL) \
|| (defined(TRC_GROUP_MINPTHPTL) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MINPTHPTL"
#define TRC_COMP MINPTHPTL
#include "minpthptl_trc.h"
#endif

/*
 * minpttest components
 */

#if defined (TRC_COMP_MINPTTEST) \
|| (defined(TRC_GROUP_MINPTTEST) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MINPTTEST"
#define TRC_COMP MINPTTEST
#include "minpttest_trc.h"
#endif

/*
 * moddbg components
 */

#if defined (TRC_COMP_MODDBG) \
|| (defined(TRC_GROUP_MODDBG) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MODDBG"
#define TRC_COMP MODDBG
#include "moddbg_trc.h"
#endif

/*
 * mpeng components
 */

#if defined (TRC_COMP_MPENG) \
|| (defined(TRC_GROUP_MPENG) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MPENG"
#define TRC_COMP MPENG
#include "mpeng_trc.h"
#endif

/*
 * mps components
 */

#if defined (TRC_COMP_MPS) \
|| (defined(TRC_GROUP_MPS) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MPS"
#define TRC_COMP MPS
#include "mps_trc.h"
#endif

/*
 * mpsbad components
 */

#if defined (TRC_COMP_MPSBAD) \
|| (defined(TRC_GROUP_MPSBAD) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MPSBAD"
#define TRC_COMP MPSBAD
#include "mpsbad_trc.h"
#endif

/*
 * mspcnt components
 */

#if defined (TRC_COMP_MPSCNT) \
|| (defined(TRC_GROUP_MSPCNT) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MPSCNT"
#define TRC_COMP MPSCNT
#include "mspcnt_mpscnt_trc.h"
#endif

/*
 * mpsdll components
 */

#if defined (TRC_COMP_MPSDLL) \
|| (defined(TRC_GROUP_MPSDLL) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MPSDLL"
#define TRC_COMP MPSDLL
#include "mpsdll_trc.h"
#endif

/*
 * mpskcnt components
 */

#if defined (TRC_COMP_MPSKCNT) \
|| (defined(TRC_GROUP_MPSKCNT) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MPSKCNT"
#define TRC_COMP MPSKCNT
#include "mpskcnt_trc.h"
#endif

/*
 * mpskstress components
 */

#if defined (TRC_COMP_MPSKSTRESS) \
|| (defined(TRC_GROUP_MPSKSTRESS) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MPSKSTRESS"
#define TRC_COMP MPSKSTRESS
#include "mpskstress_trc.h"
#endif

/*
 * mpsopen components
 */

#if defined (TRC_COMP_MPSOPEN) \
|| (defined(TRC_GROUP_MPSOPEN) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MPSOPEN"
#define TRC_COMP MPSOPEN
#include "mpsopen_trc.h"
#endif

/*
 * mpssend components
 */

#if defined (TRC_COMP_MPSSEND) \
|| (defined(TRC_GROUP_MPSSEND) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MPSSEND"
#define TRC_COMP MPSSEND
#include "mpssend_trc.h"
#endif

/*
 * mpsucnt components
 */

#if defined (TRC_COMP_MPSUCNT) \
|| (defined(TRC_GROUP_MPSUCNT) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MPSUCNT"
#define TRC_COMP MPSUCNT
#include "mpsucnt_trc.h"
#endif

/*
 * mpsumps components
 */

#if defined (TRC_COMP_MPSUMPS) \
|| (defined(TRC_GROUP_MPSUMPS) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MPSUMPS"
#define TRC_COMP MPSUMPS
#include "mpsumps_trc.h"
#endif

/*
 * mpsustress components
 */

#if defined (TRC_COMP_MPSUSTRESS) \
|| (defined(TRC_GROUP_MPSUSTRESS) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MPUSTRESS"
#define TRC_COMP MPSUSTRESS
#include "mpsustress_trc.h"
#endif

/*
 * mptestapp components
 */

#if defined (TRC_COMP_MPTESTAPP) \
|| (defined(TRC_GROUP_MPTESTAPP) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MPTESTAPP"
#define TRC_COMP MPTESTAPP
#include "mptestapp_trc.h"
#endif

/*
 * msgdisp components
 */

#if defined (TRC_COMP_MSGDISP) \
|| (defined(TRC_GROUP_MSGDISP) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "MSGDISP"
#define TRC_COMP MSGDISP
#include "msgdisp_trc.h"
#endif

/*
 * ndu components
 */

#if defined (TRC_COMP_NDU) \
|| (defined(TRC_GROUP_NDU) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "NDU"
#define TRC_COMP NDU
#include "ndu_trc.h"
#endif

#if defined (TRC_COMP_NDUADMLIB) \
|| (defined(TRC_GROUP_NDU) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "NDU"
#define TRC_COMP NDUADMLIB
#include "nduadmlib_trc.h"
#endif

#if defined (TRC_COMP_NDULIB) \
|| (defined(TRC_GROUP_NDU) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "NDU"
#define TRC_COMP NDULIB
#include "ndulib_trc.h"
#endif

/*
 * ndumon components
 */

#if defined (TRC_COMP_NDUMON) \
|| (defined(TRC_GROUP_NDUMON) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "NDUMON"
#define TRC_COMP NDUMON
#include "ndumon_trc.h"
#endif

/*
 * ndusetup components
 */

#if defined (TRC_COMP_NDUSETUP) \
|| (defined(TRC_GROUP_NDUSETUP) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "NDUSETUP"
#define TRC_COMP NDUSETUP
#include "ndusetup_trc.h"
#endif

/*
 * nduupg components
 */

#if defined (TRC_COMP_NDUUPG) \
|| (defined(TRC_GROUP_NDUUPG) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "NDUUPG"
#define TRC_COMP NDUUPG
#include "nduupg_trc.h"
#endif

/*
 * nvram components
 */

#if defined (TRC_COMP_NVRAMLIB) \
|| (defined(TRC_GROUP_NVRAM) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "NVRAM"
#define TRC_COMP NVRAMLIB
#include "nvramlib_trc.h"
#endif

#if defined (TRC_COMP_NVRAMDRV) \
|| (defined(TRC_GROUP_NVRAM) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "NVRAM"
#define TRC_COMP NVRAMDRV
#include "nvramdrv_trc.h"
#endif

/*
 * perf components
 */

#if defined (TRC_COMP_PERF) \
|| (defined(TRC_GROUP_PERF) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_COMP PERF
#include "perf_trc.h"
#endif

/*
#if defined (TRC_COMP_PERFTEST) \
#define TRC_COMP PERFTEST
#include "perftest_trc.h"
#define TRC_GROUP_NAME "PERF"
 * perftest components
 */

#if defined (TRC_COMP_PERFTEST) \
|| (defined(TRC_GROUP_PERFTEST) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "PERFTEST"
#define TRC_COMP PERFTEST
#include "perftest_trc.h"
#endif

/*
 * printdb components
 */

#if defined (TRC_COMP_PRINTDB) \
|| (defined(TRC_GROUP_PRINTDB) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "PRINTDB"
#define TRC_COMP PRINTDB
#include "printdb_trc.h"
#endif

/*
 * printstat components
 */

#if defined (TRC_COMP_PRINTSTAT) \
|| (defined(TRC_GROUP_PRINTSTAT) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "PRINTSTAT"
#define TRC_COMP PRINTSTAT
#include "printstat_trc.h"
#endif

/*
 * promote components
 */

#if defined (TRC_COMP_PROMOTE) \
|| (defined(TRC_GROUP_PROMOTE) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_COMP PROMOTE
#include "promote_trc.h"
#endif

/*
 * psmadmin components
 */

#if defined (TRC_COMP_PSMADMIN) \
|| (defined(TRC_GROUP_PSMADMIN) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_COMP PSMADMIN
#include "psmadmin_trc.h"
#endif

/*
 * psmext components
 */

#if defined (TRC_COMP_PSMEXT) \
|| (defined(TRC_GROUP_PSMEXT) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "PSMEXT"
#define TRC_COMP PSMEXT
#include "psmext_trc.h"
#endif

/*
 * psmmenu components
 */

#if defined (TRC_COMP_PSMMENU) \
|| (defined(TRC_GROUP_PSMMENU) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "PSMMENU"
#define TRC_COMP PSMMENU
#include "psmmenu_trc.h"
#endif

/*
 * psmregress components
 */

#if defined (TRC_COMP_PSMREGRESS) \
|| (defined(TRC_GROUP_PSMREGRESS) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "PSMREGRESS"
#define TRC_COMP PSMREGRESS
#include "psmregress_trc.h"
#endif

/*
 * psmsys components
 */

#if defined (TRC_COMP_PSMSYS) \
|| (defined(TRC_GROUP_PSMSYS) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "PSMSYS"
#define TRC_COMP PSMSYS
#include "psmsys_trc.h"
#endif

/*
 * reboot components
 */

#if defined (TRC_COMP_REBOOT) \
|| (defined(TRC_GROUP_REBOOT) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "REBOOT"
#define TRC_COMP REBOOT
#include "reboot_trc.h"
#endif

/*
 * redir components
 */

#if defined (TRC_COMP_REDIR) \
|| (defined(TRC_GROUP_REDIR) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "REDIR"
#define TRC_COMP REDIR
#include "redir_trc.h"
#endif

/*
 * remove components
 */

#if defined (TRC_COMP_REMOVE) \
|| (defined(TRC_GROUP_REMOVE) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "REMOVE"
#define TRC_COMP REMOVE
#include "remove_trc.h"
#endif

/*
 * rmcui components
 */

#if defined (TRC_COMP_RMCUI) \
|| (defined(TRC_GROUP_RMCUI) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "RMCUI"
#define TRC_COMP RMCUI
#include "rmcui_trc.h"
#endif

/*
 * rmiotest components
 */

#if defined (TRC_COMP_RMIOTEST) \
|| (defined(TRC_GROUP_RMIOTEST) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "RMIOTEST"
#define TRC_COMP RMIOTEST
#include "rmiotest_trc.h"
#endif

/*
 * rmiradmin components
 */

#if defined (TRC_COMP_RMIRADMIN) \
|| (defined(TRC_GROUP_RMIRADMIN) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "RMIRADMIN"
#define TRC_COMP RMIRADMIN
#include "rmiradmin_trc.h"
#endif

/*
 * rmirconfig components
 */

#if defined (TRC_COMP_RMIRCONFIG) \
|| (defined(TRC_GROUP_RMIRCONFIG) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "RMIRCONFIG"
#define TRC_COMP RMIRCONFIG
#include "rmirconfig_trc.h"
#endif

/*
 * rmirdb components
 */

#if defined (TRC_COMP_RMIRDB) \
|| (defined(TRC_GROUP_RMIRDB) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "RMIRDB"
#define TRC_COMP RMIRDB
#include "rmirdb_trc.h"
#endif

/*
 * rmirfailo components
 */

#if defined (TRC_COMP_RMIRFAILO) \
|| (defined(TRC_GROUP_RMIRFAILO) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "RMIRFAILO"
#define TRC_COMP RMIRFAILO
#include "rmirfailo_trc.h"
#endif

/*
 * rmirmir components
 */

#if defined (TRC_COMP_RMIRMIR) \
|| (defined(TRC_GROUP_RMIRMIR) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "RMIRMIR"
#define TRC_COMP RMIRMIR
#include "rmirmir_trc.h"
#endif

/*
 * rmirsys components
 */

#if defined (TRC_COMP_RMIRSYS) \
|| (defined(TRC_GROUP_RMIRSYS) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "RMISYS"
#define TRC_COMP RMIRSYS
#include "rmirsys_trc.h"
#endif

/*
 * rmirtrans components
 */

#if defined (TRC_COMP_RMIRTRANS) \
|| (defined(TRC_GROUP_RMIRTRANS) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "RMIRTRANS"
#define TRC_COMP RMIRTRANS
#include "rmirtrans_trc.h"
#endif

/*
 * rmiruser components
 */

#if defined (TRC_COMP_RMIRUSER) \
|| (defined(TRC_GROUP_RMIRUSER) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "RMIRUSER"
#define TRC_COMP RMIRUSER
#include "rmiruser_trc.h"
#endif

/*
 * rmirutil components
 */

#if defined (TRC_COMP_RMIRUTIL) \
|| (defined(TRC_GROUP_RMIRUTIL) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "RMIRUTIL"
#define TRC_COMP RMIRUTIL
#include "rmirutil_trc.h"
#endif

/*
 * rmtagent components
 */

#if defined (TRC_COMP_RMTAGENT) \
|| (defined(TRC_GROUP_RMTAGENT) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "RMTAGENT"
#define TRC_COMP RMTAGENT
#include "rmtagent_trc.h"
#endif

/*
 * rmtbroker components
 */

#if defined (TRC_COMP_RMTBROKER) \
|| (defined(TRC_GROUP_RMTBROKER) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "RMTBROKER"
#define TRC_COMP RMTBROKER
#include "rmtbroker_trc.h"
#endif

/*
 * rmtgui components
 */

#if defined (TRC_COMP_RMTGUI) \
|| (defined(TRC_GROUP_RMTGUI) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "RMTGUI"
#define TRC_COMP RMTGUI
#include "rmtgui_trc.h"
#endif

/*
 * rmttest components
 */

#if defined (TRC_COMP_RMTTEST) \
|| (defined(TRC_GROUP_RMTTEST) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "RMTTEST"
#define TRC_COMP RMTTEST
#include "rmttest_trc.h"
#endif

/*
 * RollBack driver
 */

#if defined (TRC_COMP_ROLLBACK) \
|| (defined(TRC_GROUP_ROLLBACK) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_COMP ROLLBACK
#include "rollback_trc.h"
#endif

/*
 * serial components
 */

#if defined (TRC_COMP_SERIALDRVR) \
|| (defined(TRC_GROUP_SERIAL) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "SERIAL"
#define TRC_COMP SERIALDRVR
#include "serialdrvr_trc.h"
#endif

/*
 * setdrvr components
 */

#if defined (TRC_COMP_SETDRVR) \
|| (defined(TRC_GROUP_SETDRVR) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "SETDRVR"
#define TRC_COMP SETDRVR
#include "setdrvr_trc.h"
#endif

/*
 * setimg components
 */

#if defined (TRC_COMP_SETIMG) \
|| (defined(TRC_GROUP_SETIMG) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "SETIMG"
#define TRC_COMP SETIMG
#include "setimg_trc.h"
#endif

/*
 * setmir components
 */

#if defined (TRC_COMP_SETMIR) \
|| (defined(TRC_GROUP_SETMIR) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "SETMIR"
#define TRC_COMP SETMIR
#include "setmir_trc.h"
#endif

/*
 * simputil components
 */

#if defined (TRC_COMP_SIMPUTIL) \
|| (defined(TRC_GROUP_SIMPUTIL) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "SIMPUTIL"
#define TRC_COMP SIMPUTIL
#include "simputil_trc.h"
#endif

/*
 * snapadmin components
 */

#if defined (TRC_COMP_SNAPADMIN) \
|| (defined(TRC_GROUP_SNAPADMIN) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "SNAPADMIN"
#define TRC_COMP SNAPADMIN
#include "snapadmin_trc.h"
#endif

/*
 * snapdrvr components
 */

#if defined (TRC_COMP_SNAPDRVR) \
|| (defined(TRC_GROUP_SNAPDRVR) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_COMP SNAPDRVR
#include "snapdrvr_trc.h"
#endif

/*
 * template components
 */

#if defined (TRC_COMP_TEMPLATEDRVR) \
|| (defined(TRC_GROUP_TEMPLATEDRVR) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_COMP TEMPLATEDRVR
#include "templatedrvr_trc.h"
#endif

/*
 * snapk10adm components
 */

#if defined (TRC_COMP_SNAPK10ADM) \
|| (defined(TRC_GROUP_SNAPK10ADM) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_COMP SNAPK10ADM
#include "snapk10adm_trc.h"
#endif

/*
 * spid components
 */

#if defined (TRC_COMP_SPID) \
|| (defined(TRC_GROUP_SPID) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "SPID"
#define TRC_COMP SPID
#include "spid_trc.h"
#endif

/*
 * svccmi components
 */

#if defined (TRC_COMP_SVCCMI) \
|| (defined(TRC_GROUP_SVCCMI) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "SVCCMI"
#define TRC_COMP SVCCMI
#include "svccmi_trc.h"
#endif

/*
 * svccmitest components
 */

#if defined (TRC_COMP_SVCCMITEST) \
|| (defined(TRC_GROUP_SVCCMITEST) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "SVCCMITEST"
#define TRC_COMP SVCCMITEST
#include "svccmitest_trc.h"
#endif

/*
 * svccmitf components
 */

#if defined (TRC_COMP_SVCCMITF) \
|| (defined(TRC_GROUP_SVCCMITF) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "SVCCMITF"
#define TRC_COMP SVCCMITF
#include "svccmitf_trc.h"
#endif

/*
 * svcndu components
 */

#if defined (TRC_COMP_SVCNDU) \
|| (defined(TRC_GROUP_SVCNDU) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "SVCNDU"
#define TRC_COMP SVCNDU
#include "svcndu_trc.h"
#endif

/*
 * svcscd components
 */

#if defined (TRC_COMP_SVCSCD) \
|| (defined(TRC_GROUP_SVCSCD) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "SVCSCD"
#define TRC_COMP SVCSCD
#include "svcscd_trc.h"
#endif

/*
 * svcscdtest components
 */

#if defined (TRC_COMP_SVCSCDTEST) \
|| (defined(TRC_GROUP_SVCSCDTEST) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "SVCSCDTEST"
#define TRC_COMP SVCSCDTEST
#include "svcscdtest_trc.h"
#endif

/*
 * svcscdtf components
 */

#if defined (TRC_COMP_SVCSCDTF) \
|| (defined(TRC_GROUP_SVCSCDTF) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "SVCSCDTF"
#define TRC_COMP SVCSCDTF
#include "svcscdtf_trc.h"
#endif

/*
 * sym8751 components
 */

#if defined (TRC_COMP_SYM8751) \
|| (defined(TRC_GROUP_SYM8751) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "SYM8751"
#define TRC_COMP SYM8751
#include "sym8751_trc.h"
#endif

/*
 * tcd components
 */

#if defined (TRC_COMP_TCD) \
|| (defined(TRC_GROUP_TCD) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "TCD"
#define TRC_COMP TCD
#include "tcd_trc.h"
#endif

/*
 * tdd components
 */

#if defined (TRC_COMP_TDD) \
|| (defined(TRC_GROUP_TDD) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "TDD"
#define TRC_COMP TDD
#include "tdd_trc.h"
#endif

/*
 * tester components
 */

#if defined (TRC_COMP_TESTER) \
|| (defined(TRC_GROUP_TESTER) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "TESTER"
#define TRC_COMP TESTER
#include "tester_trc.h"
#endif

/*
 * testlddrvr2 components
 */

#if defined (TRC_COMP_TESTLDDRVR2) \
|| (defined(TRC_GROUP_TESTLDDRVR2) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "TESTLDDRVR2"
#define TRC_COMP TESTLDDRVR2
#include "testlddrvr2_trc.h"
#endif

/*
 * testldrvr components
 */

#if defined (TRC_COMP_TESTLDRVR) \
|| (defined(TRC_GROUP_TESTLDRVR) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_COMP TESTLDRVR
#include "testldrvr_trc.h"
#endif

/*
 * testld components
 */

#if defined (TRC_COMP_TESTTLD) \
|| (defined(TRC_GROUP_TESTLD) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "TESTLD"
#define TRC_COMP TESTTLD
#include "testld_testtld_trc.h"
#endif

/*
 * flare components
 */

#if defined (TRC_COMP_TRC) \
|| (defined(TRC_GROUP_FLARE) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#if !defined(TRC_FLARE_HACK)
#define TRC_GROUP_NAME "FLARE"
#endif
#define TRC_COMP TRC
#include "flare_trc_trc.h"
#endif

/*
 * unbind components
 */

#if defined (TRC_COMP_UNBIND) \
|| (defined(TRC_GROUP_UNBIND) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "UNBIND"
#define TRC_COMP UNBIND
#include "unbind_trc.h"
#endif

/*
 * uptest components
 */

#if defined (TRC_COMP_UPTEST) \
|| (defined(TRC_GROUP_UPTEST) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "UPTEST"
#define TRC_COMP UPTEST
#include "uptest_trc.h"
#endif

/*
 * utestappa components
 */

#if defined (TRC_COMP_UTESTAPPA) \
|| (defined(TRC_GROUP_UTESTAPPA) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "UTESTAPPA"
#define TRC_COMP UTESTAPPA
#include "utestappa_trc.h"
#endif

/*
 * utestappb components
 */

#if defined (TRC_COMP_UTESTAPPB) \
|| (defined(TRC_GROUP_UTESTAPPB) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "UTESTAPPB"
#define TRC_COMP UTESTAPPB
#include "utestappb_trc.h"
#endif

/*
 * tmos  components
 */

#if defined (TRC_COMP_TMOS) \
|| (defined(TRC_GROUP_TMOS) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_COMP TMOS
#include "tmos_trc.h"
#endif

/*
 * kdbm export driver components
 */

#if defined (TRC_COMP_KDBMEXP) \
|| (defined(TRC_GROUP_KDBMEXP) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "KDBMEXP"
#define TRC_COMP KDBMEXP
#include "kdbmexp_trc.h"
#endif

/*
 * kdbm debug exenstion components
 */

#if defined (TRC_COMP_KDBMEXT) \
|| (defined(TRC_GROUP_KDBM) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_GROUP_NAME "KDBMEXT"
#define TRC_COMP KDBMEXT
#include "kdbmext_trc.h"
#endif

/*
 *  Zero Fill Library Components
 */
#if defined (TRC_COMP_ZEROFILLLIB) \
|| (defined(TRC_GROUP_ZEROFILLLIB) && TRC_GEN_GROUP)
#if defined(TRC_GEN_GROUP)
#undef TRC_COMP
#endif
#define TRC_COMP ZEROFILLLIB
#include "Zero_Fill_Lib_trc.h"
#endif


/*
 * verify that a component was defined
 */
#if !defined(TRC_COMP) \
 && !defined(TRC_GEN_GROUP)
#error TRC_COMP_<COMPONENT> was not defined
#endif

#endif /* !defined(TRC_ENVIRON1_H) */ /* last line in file */
