/************************************************************************
*
*  Copyright (c) 2002, 2005-2006 EMC Corporation.
*  All rights reserved.
*
*  ALL RIGHTS ARE RESERVED BY EMC CORPORATION.  ACCESS TO THIS
*  SOURCE CODE IS STRICTLY RESTRICTED UNDER CONTRACT. THIS CODE IS TO
*  BE KEPT STRICTLY CONFIDENTIAL.
*
*  UNAUTHORIZED MODIFICATIONS OF THIS FILE WILL VOID YOUR SUPPORT
*  CONTRACT WITH EMC CORPORATION.  IF SUCH MODIFICATIONS ARE FOR
*  THE PURPOSE OF CIRCUMVENTING LICENSING LIMITATIONS, LEGAL ACTION
*  MAY RESULT.
*
************************************************************************/


#ifndef __FctIoctls_h__
#define __FctIoctls_h__

//++
// File Name: FctIoctls.h
//    
//
// Contents:
//      Defines the IOCTLs of the Cached Volume driver.  
//
// Revision History:
//--

// Define the various device type values.  Note that values used by Microsoft Corporation
// are in the range 0-32767, and 32768-65535 are reserved for use by customers.  (Quoted
// from "/ddk/inc/devioctl.h".)
#define FILE_DEVICE_FCT_VOLUME          0x80FF  // unique in devioctl.h

#define IOCTL_FCT_CLEAR_CACHE_DIRTY \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x800, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#define IOCTL_FCT_GET_VOL_STATS \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x801, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)
    
#define IOCTL_FCT_CLEAR_VOL_STATS \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x802, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#define IOCTL_FCT_GET_FULL_VOL_INFO \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x803, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#define IOCTL_FCT_AIDVD_SIGNAL_DRIVER \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x804, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#define IOCTL_FCT_REINITILIZE_CACHE \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x805, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#define IOCTL_FCT_CHECK_AND_CLEANUP_STALE_RECORD \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x806, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#define IOCTL_FCT_REVIVE_CACHE \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x807, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#define IOCTL_FCT_SUSPEND_CACHE \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x808, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#define IOCTL_FCT_SET_DEVICE_QUEUE_DEPTH_LIMIT \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x809, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#define IOCTL_FCT_SET_PROMOTE_LIMIT \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x80a, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#define IOCTL_FCT_SET_FLUSH_LIMIT \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x80b, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#define IOCTL_FCT_CLEAN_DB \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x80c, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#define IOCTL_FCT_GET_ENUM_VOLS \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x80d, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#define IOCTL_FCT_PROMOTE_PAGE \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x80e, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

// Deprecated
//#define IOCTL_FCT_GET_REAL_WWN \
//    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x80f, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#define IOCTL_FCT_GET_CACHE_DEVICE_ZEROFILL_INFO \
		EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x8fa, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#define IOCTL_FCT_GET_PROMOTED_PAGES_ON_ALL_DEVICES \
		EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x8fb, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#define IOCTL_FCT_ENABLE_EXPANSION_DEBUG \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x8fc, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)
    
#define IOCTL_FCT_CACHE_DEVICE_PROMOTED_PAGES \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x8fd, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#define IOCTL_FCT_SIM_RAP_GET_VOLUME_PIN_STATES \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x8fe, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#define IOCTL_FCT_SIM_RAP_ENABLE_PIN_FAILURES \
    EMCPAL_IOCTL_CTL_CODE(FILE_DEVICE_FCT_VOLUME, 0x8ff, EMCPAL_IOCTL_METHOD_BUFFERED, EMCPAL_IOCTL_FILE_ANY_ACCESS)

#endif  // __FctIoctls_h__

