// K10EFDCacheAdminExport.h
//
// Copyright (C) 2009	EMC Corporation
//
//
//
//	Revision History
//	----------------
//
//////////////////////////////////////////////////////////////////////

#ifndef K10_EFDC_ADMIN_EXPORT_H
#define K10_EFDC_ADMIN_EXPORT_H

#include "k10defs.h"


#define K10_EFD_CACHE_ADMIN_LIB_NAME		"K10EFDCacheAdmin"
#define EFDC_DEVICE_NAME_CHAR      "\\\\.\\FctDrvr"

#define EFDC_ERROR_BASE  0x713B0000

enum EFDC_ADMIN_ERROR
{
    EFDC_ADMIN_ERROR_SUCCESS = 0x00000000L,    //  The operation completed successfully.


	EFDC_ADMIN_ERROR_WARNING_MIN = EFDC_ERROR_BASE | K10_COND_WARNING,
	EFDC_ADMIN_WARNING_CONFIG_FILE_REWRITTEN = EFDC_ADMIN_ERROR_WARNING_MIN,
    EFDC_ADMIN_WARNING_STALE_RECORD_REMOVED,
	EFDC_ADMIN_WARNING_GENERIC,	
    EFDC_ADMIN_ERROR_WARNING_MAX = EFDC_ADMIN_WARNING_GENERIC,

	EFDC_ADMIN_ERROR_ERROR_MIN = EFDC_ERROR_BASE | K10_COND_ERROR,	//  Min of the error codes.
    EFDC_ADMIN_ERROR_TLD_ERROR,
    EFDC_ADMIN_ERROR_NOT_DISABLED,
    EFDC_ADMIN_ERROR_LUN_NOT_DISABLED,
    EFDC_ADMIN_ERROR_CANT_GET_VOL_STATUS,
    EFDC_ADMIN_ERROR_CANT_GET_DRIVER_STATUS,
    EFDC_ADMIN_ERROR_CACHING_DEVICE_NOT_FOUND,
    EFDC_ADMIN_ERROR_CACHING_DEVICE_NOT_EMPTY,
    EFDC_ADMIN_ERROR_CACHING_DEVICE_INVALID_STATE,
    EFDC_ADMIN_ERROR_NO_DEVMAP,
    EFDC_ADMIN_ERROR_NO_CACHING_DEVICE_SLOTS,
    EFDC_ADMIN_ERROR_DRIVER_UPDATE,
    EFDC_ADMIN_ERROR_COMPLETION_DATA_ERROR,
    EFDC_ADMIN_ERROR_CONSUME,
    EFDC_ADMIN_ERROR_UNCONSUME,
    EFDC_ADMIN_ERROR_WORKLIST_DATA,
    EFDC_ADMIN_ERROR_STALE_RECORD_REMOVAL_FAILED,
    EFDC_ADMIN_ERROR_LUN_NOT_IN_MAP,
    EFDC_ADMIN_ERROR_GENERIC,
    EFDC_ADMIN_ERROR_ERROR_MAX = EFDC_ADMIN_ERROR_GENERIC	//  Max of the error codes.
};

#endif
