/**********************************************************************
 *  Copyright (C)  EMC Corporation 2014
 *  All rights reserved.
 *  Licensed material - property of EMC Corporation.
 **********************************************************************/

/*!*************************************************************************
 * @file fbe_test_esp_fup_manifest.c
 ***************************************************************************
 *
 * @brief
 *  The routines in this file contains the CDES-2 manifest strings.
 *  They are used to create the CDES-2 manifest files for the simulation.
 *
 * @version
 *   12-Sep-2014:  PHE - Created.
 *
 ***************************************************************************/
#include "fbe/fbe_types.h"

fbe_char_t * lcc_manifest_str =
"{\n"
" \"version\": 0, \n"
"  \"packages\": [\n"
"    {\n"
"      \"subenclosures\": [\n"
"        \"Cayenne LCC\"\n"
"      ], \n"
"      \"files\": [\n"
"        {\n"
"          \"image\": \"istr.bin\",\n"
"          \"sha1\": \"6bd3dc6706151f53edf7d5bd38d7a8ba1495613e\",\n"
"          \"version\": \"0.6.0\",\n"
"          \"component_type\": 2\n"
"        },\n"
"        {\n"
"          \"image\": \"cdes_rom.bin\",\n"
"          \"sha1\": \"f4dc213bd342149d4384004b242dbe0ba0cff9ed\",\n"
"          \"version\": \"0.9.0\",\n"
"          \"component_type\": 0\n"
"        }\n"
"      ]\n"
"    }, \n"
"    {\n"
"      \"subenclosures\": [\n"
"        \"Cayenne IOSXP\",\n"
"        \"Ancho LCC\",\n"
"        \"Tabasco LCC\",\n"
"        \"Naga IOSXP\",\n"
"        \"Oberon LCC\",\n"
"        \"Europa LCC\",\n"
"        \"Lapetus BM\"\n"
"      ],\n"
"      \"files\": [\n"
"        {\n"
"          \"image\": \"cdef.bin\",\n"
"          \"sha1\": \"b40e9e3339ca66dc1416a4bf762cae9e316c0baa\",\n"
"          \"version\": \"00.15-transfr\",\n"
"          \"component_type\": 3\n"
"        },\n"
"        {\n"
"          \"image\": \"istr.bin\", \n"
"          \"sha1\": \"6bd3dc6706151f53edf7d5bd38d7a8ba1495613e\",\n"
"          \"version\": \"0.6.0\", \n"
"          \"component_type\": 2\n"
"        }, \n"
"        {\n"
"          \"image\": \"cdes_rom.bin\", \n"
"          \"sha1\": \"f4dc213bd342149d4384004b242dbe0ba0cff9ed\", \n"
"          \"version\": \"0.9.0\", \n"
"          \"component_type\": 0\n"
"        }\n"
"      ]\n"
"    }, \n"
"    {\n"
"      \"subenclosures\": [\n"
"        \"Cayenne DRVSXP\",\n"
"        \"Naga DRVSXP\",\n"
"        \"Colossus LCC\"\n"
"      ], \n"
"      \"files\": [\n"
"        {\n"
"          \"image\": \"cdef_dual.bin\", \n"
"          \"sha1\": \"1c71e4729568f265aefc23c4994c6676401bf904\", \n"
"          \"version\": \"00.15-transfr\", \n"
"          \"component_type\": 3\n"
"        }, \n"
"        {\n"
"          \"image\": \"istr.bin\", \n"
"          \"sha1\": \"6bd3dc6706151f53edf7d5bd38d7a8ba1495613e\", \n"
"          \"version\": \"0.6.0\", \n"
"          \"component_type\": 2\n"
"        }, \n"
"        {\n"
"          \"image\": \"cdes_rom.bin\", \n"
"          \"sha1\": \"f4dc213bd342149d4384004b242dbe0ba0cff9ed\", \n"
"          \"version\": \"0.9.0\", \n"
"          \"component_type\": 0\n"
"        }\n"
"      ]\n"
"    }\n"
"  ]\n"
"}\n"
;

fbe_char_t * ps_manifest_str =
"{\n"
" \"version\": 0, \n"
"  \"packages\": [\n"
"    {\n"
"      \"subenclosures\": [\n"
"        \"000B0033\"\n"
"      ], \n"
"      \"files\": [\n"
"        {\n"
"          \"image\": \"juno2.bin\", \n"
"          \"sha1\": \"ac9b883715425e14a72694e29c2bd6f3d769e863\", \n"
"          \"version\": \"02.28\"\n"
"          \"component_type\": 4\n"
"        }\n"
"      ], \n"
"    }, \n"
"    {\n"
"      \"subenclosures\": [\n"
"        \"000B002F\"\n"
"      ],\n"
"      \"files\": [\n"
"        {\n"
"          \"image\": \"laserbeak.bin\",\n"
"          \"sha1\": \"b2b4fc5b0b925de8bd817c7ac8c91e552f3e9a56\",\n"
"          \"version\": \"05.01\"\n"
"          \"component_type\": 4\n"
"        }\n"
"      ],\n"
"    },\n"
"    {\n"
"      \"subenclosures\": [\n"
"        \"000B0027\", \n"
"        \"000B0028\"\n"
"      ], \n"
"      \"files\": [\n"
"        {\n"
"          \"image\": \"3gve.bin\", \n"
"          \"sha1\": \"9b2e3a344e6ecf261ccdc039c28dc492bd66a621\", \n"
"          \"version\": \"04.21\"\n"
"          \"component_type\": 4\n"
"        }\n"
"      ], \n"
"    }, \n"
"    {\n"
"      \"subenclosures\": [\n"
"        \"000B0035\"\n"
"      ], \n"
"      \"files\": [\n"
"        {\n"
"          \"image\": \"octane.bin\", \n"
"          \"sha1\": \"623aa0df1ba05942a987cfbea046e77aa0203058\", \n"
"          \"version\": \"09.07\"\n"
"          \"component_type\": 4\n"
"        }\n"
"      ],\n" 
"    }\n"
"  ]\n"
"}\n"
;
